Marie est gentille
Il ne se couche pas tres tot
he doesn't go to bed very early
He doesn't wake up before eleven o'clock
Ils ne se reveille pas avant onze heures!
*** Practice <2025-04-01 Tue 09:24>
je veux beaucoup de photos
la photo
We are traveling with paul
Nous voyageons avec paul
j'ai trois filles
Il ne veut pas partir avec eux
He does not want to leave with them
There is too much salt in this dish it's not good 
Il y a trop de sel dans ce plat, ce n'est pas bon
Nous voyageons avec paul
They are by the castle
Ils vont au chateau
*** Practice <2025-04-01 Tue 09:24>
*** Unit__ <2025-04-01 Tue 09:24>

Paul pense que tres mauvais
Ces actrices sont tres intelligents 
Do you know my parents
Connais tu mes parents
Tu connais me parents
Il aime beacoup les films americains
elle pense quoi de ce livre
j'aime penser
C'est mon film prefere. This is my favorite movie
cet acteur est genial!
je pense que ce film est mauvais
C'est mon film prefere
ce film est mauvais
je suis d'accord avec eux
paul pense que
 ce film est vraiment super. Je suis d'accord, je pense qui'l n'est pas bon
je pense que cette robe est super
cet acteur est genial
ce film est tres amusant! et les acteurs sont geniaux.
il y a des fleurs dans le jardin
ready pret

le chef prepare trois repas audjourd'hui
les garcons
tu aimes le francais

tes voisins sont gentils

elles sont en france

mes voiusins sont gentils
my neighbors are kind

tu aimes le chocolat
do you like chocolate

il y a des fleurs dans le jardin

il y a des chats et des chiens





