* 25,500 BCE
** Namibia.
*** D c. 25,500-25,300 BCE.
**** M: Charcoal on stone. 
- 7 stone fragments, several w/ familiar images of animals in characteristic profile - named after Apollo 11 moon landing (cave discovered at this time)	Apollo 11 stones
Lascaux, France. Paleolithic Europe. 15,000-13,000 BCE. Rock painting. - paint made w/ natural products - paint colors bound with animal fat - 650 paintings; most common cows, bulls horses, deer - paintings far from entrance - profile view; some appear pregnant - many overlapping figures - evidence still visible of scaffolding - evidence some people sought shelter at mouth of caves - walls scraped for even surface - flat stones as palettes - theories: ensured successful hunt, ancestral animal worship, might have flung spears for target practice	
* 14,000 - 7000 BCE.
** - Tequixquiac
L: central Mexico. 
D: 14,000-7000 BCE. 
M: Bone. 
- from camel-like animal - bone worked to create image/skull of dog/wolf - one natural form used to take the shape of another -
  found in 1870 - Mesoamerican idea: a sacrum is a ""second skull"" -
  important role in traditions - representative of doorways that permitted spirits/deities to enter physical world"
  Camelid sacrum in the shape of a canine	
** Arabian Peninsula. 
D:Fourth millennium BCE. 
M:Sandstone
- one of earliest known works of art from Arabia - found in area w/ extensive ancient trade routes, near Ha'il (features tombs carved into sandstone cliffs) - religious/burial purpose - belted robe that a double-bladed knife/sword hangs from	
** Anthropomorphic stele	
*** Liangzhu, China. 
**** D: 3300-2200 BCE. 
***** M: Carved jade.
- abstract designs: main decoration is a face pattern (w/ human and animal influences), maybe of spirits/deities - corners w/ mask-like images w/ pronounced eyes and fanged mouth - in burials of people of high rank - jade liked with virtues of durability, subtlety, beauty - Neolithic era
** Jade cong	
Ambum Valley, Enga Province,
Papua New Guinea. c. 1500 BCE.
Greywacke. - Stone Age - composite human/animal figure (anteater head + human body?) - theorized to be a pestle, maybe w/ ritual purpose	
** The Ambum Stone	
Central Mexico, site of Tlatilco. 
D: 1200-900 bce. 
M: Ceramic. - 
many shapes and forms - detailed hair styles, clothing, body ornaments - many w/ deformities, including 2-headed (Siamese twins?) - shamanistic function? - fertility cult practices?	Tlatilco Female Figures	
Lapita. Reef Islands, Solomon Islands. 1000 BCE. Terra cotta (incised). - Lapita peoples (in the Pacific) known for pottery - characteristic use of curved stamped patterns (dots, 
circles, hatching) - outlined forms - one of oldest human faces in Oceanic Art	
Terra-cotta fragment	
** Great Hall of the Bulls	
Tassili n'Ajjer, Algeria. 
*** D: 6000-4000 BCE. Pigment on rock.
 - more than 15,000 drawings/engravings found at site - once grasslands, now desert - drawing varied - livestock, wildlife, humans - site probably painted by many different groups over long time - bodypaint and horns evidence of ceremonial attire - much larger than other beings in image - representation of deity/woman participating in ritual?	
** Running Horned Woman	
Susa, Iran. 
4200-3500 bce. 
Painted terra cotta. - 
found near burial site, along with hundreds of baskets, bowls, metallic items - use of potter's wheel - thin walls of pot - stylized aquatic birds on top; stylized running dogs w/ long narrow bodies on bottom - middle of horns: clan symbol of family ownership - identifies deceased as belonging to particular group/family? - geometric patterns - evidence indicates used in secondary burial rituals where remains moved to another burial area after flesh removed	Beaker with ibex motifs	
** Wiltshire, UK. Neolithic Europe.
c. 2500-1600 BCE.
Sandstone.
- maybe took 100 years to build over time - post-and-lintel building w/ mortise-and-tenon - large megaliths in center > 20 ft tall; form horseshoe surrounding central flat stone - ring of megaliths (originally w/ lintels) surrounding horseshoe - very heavy stones - hundreds of smaller stones around monument - some stones imported from > 200 miles  - thought to be oriented toward sunrise on summer solstice or predict eclipse - new theory: center of ceremonies concerning death and burial - one of many henges in southern England
** Stonehenge	
Rome, Italy. Late Antique Europe.
c. 200-400 CE.
Excavated tufa and fresco.
- 4 million dead and extend for about 100 miles - contains the tombs of 7 popes and many early Christian martyrs - Greek Chapel: named for two Greek inscriptions painted on the right niche; three niches for sarcophagi; decorated w/ paintings in the Pompeian style: sketchy painterly brushstrokes - Orants Figure: fresco over a tomb niche set over an arched wall (cemetery of a family vault); arms outstretched in prayer; figure compact, dark, set off from a light background; terse angular contours; emphatic gestures; left: painting of a teacher w/ children; right: mother and child (maybe Mary with Christ or the Church) - Good Shepherd Fresco: restrained portrait of Christ as a Good Shepherd; stories of the life of the Old Testament Prophet Jonah often appear in lunettes; Jonah's regurgitation from the mouth of a big fish is seen as prefiguring Christ's resurrection - parallels between Old and New Testament stories feature prominently in Early Christian art; Christians see this as a fulfillment of the Hebrew scriptures - named after wife of a Roman consul?	
** Catacomb of Priscilla	
Rome, Italy. Late Antique Europe. 
c. 422-432 CE. 
Brick and stone, wooden roof. - 
three-aisled basilica; no transepts - long tall, broad nave; axial plan - spolia: tall slender columns taken from the Temple of Juno in Rome, erected on this site; statement about the triumph of Christianity over paganism - windows made of selenite  - flat wooden roof; coffered ceiling; thin walls support light roof - bare exterior, sensitively decorated interior (covered with marble veneer): representing the Christian whose exterior may be gross, but whose interior soul is beautiful - as in Jewish tradition, men and women stood separately; men stood in main aisle, women in side aisles w/ partial view	Santa Sabina	
** "Constantinople (Istanbul). Anthemius of Tralles and Isidorus of Miletus.
532-537 CE. Brick and ceramic elements with stone and mosaic veneer. - ""Holy Wisdom"" - combination of centrally planned and axially planned church - exterior: plain and massive, little decoration - interior: altar at end of nave, but emphasis placed over area covered by dome; cornice unifies space; arcade decoration: wall and capitals flat and thin by richly ornamented; large fields for mosaic decoration (at one time had four acres of gold mosaics on walls); many windows punctuate wall spaces - dome supported by pendentives (first time every); 40 windows at base symbolically acting as halo over congregation when filled w/ light - minarets added in Islamic period, when Hagia Sophia functioned as a mosque; now a museum; marble columns appropriated from Rome, Ephesus, and other Greek sites; capitals avoid classical allusions; surfaces contain deeply cut acanthus leaves - patrons: Emperor Justinian and Empress Theodora; commissioned work after burning of original building in Nike Revolt of 532"

** Hagia Sophia	
Ravenna, Italy. Early Byzantine Europe. 
c. 526-547 CE. Brick, marble, and stone veneer; mosaic. - 8-sided church; two concentric octagons - plain exterior except porch added later in Renaissance - large windows for illuminating interior designs - interior w/ thin columns and open arched spaces; dematerialize mass of structure - martyrium - banker Julianus Argentarius financed building of	San Vitale	
- left: clergy; right: military - dressed in royal purple and gold - symmetry, frontality - holds paten - slight impression of procession forward - figures w/o volume; seem to float and overlap at each other's feet - minimal background: green base at feet, golden background indicates timelessness - archbishop Maximianus identified, only participant labelled - halo indicates saintliness, semi-divinity as head of church and state - Justinian and Theodora actively participating in Mass; position over altar enhances this allusion	Justinian and Attendants (from San Vitale)	
- slight displacement of absolute symmetry w/ Theodora; plays secondary role to husband - richly robed empress and ladies at court - stands in architectural framework, holding chalice for mass; about to go behind curtain - figures flattened and weightless, barely a hint of a body can be detected beneath drapery - Three Magi depicted on hem of dress, drawing parallels between Theodora and Magi - figures elongated and generalized; floating feet	Theodora and Attendants (from San Vitale)	

Early Byzantine Europe. Early sixth century CE. Illuminated manuscript (tempera, gold, and silver on purple vellum). - style: lively, softly modeled figures; classical training of artists: contrapposto, foreshortening, shadowing, perspective; shallow settings; fluid movement of decorated figures; richly colored and shaded; two rows linked by a bridge/pathway; text placed above illustrations - technique and origin: silver script now oxidized and turned black; origin uncertain: Constantinople? antioch? maybe done in royal workshop: purple parchment hallmark of royal institution; genesis stories are done in continuous narrative w/ genre details; written in Greek; partial manuscript but illustrations survive; first surviving illustrations of stories from Genesis - Rebecca and Eliezer at the Well: Genesis 24: 15-16; Rebecca emerges from city of Nahor w/ jar on shoulder for spring water; quenches thirst of camel driver and camels; colonnaded road leads to spring; Roman water goddess personifies spring - Jacob Wrestling the Angel: Genesis 32: 22-31; Jacob takes two wives, two maids, and eleven children (number of children abbreviated) and crosses a river; Roman-looking bridge; at night wrestles angel, who strikes him on hip socket

Rebecca and Eliezer at the Well and Jacob Wrestling the Angel, from the Vienna Genesis	


Early Byzantine Europe. Sixth or early seventh century CE. Encaustic on wood. - icon placed in medieval monastery - Virgin and Child centrally placed; firmly modeled - Mary as Theotokos; looks beyond viewer as if seeing into futures - Christ Child looks away, perhaps anticipating crucifixion - Saints Theodore and George; warrior saints; stiff and hieratic; engage viewer directly - angles look toward heaven, where descending hand of God comes down to bless scene; painted in classical style w/ brisk brushwork	Virgin (Theotokos) and Child between Saints Theodore and George	

* 1100 - 1500 

** Chartres, France.
Gothic Europe. Original construction 
c. 1145-1155 CE; 
reconstructed 
c. 1194-1220 CE. Limestone, stained glass. 
- fire in 1194 forced reconstruction of everything except facade - dedicated to Mary (Marian shrine) - Mary's tunic worn at Jesus's birth most sacred relic; escaped fire and seen as signal to rebuild; believed to have healing powers - right spire from 1160; left conceived in different style: more elaborate and decorative - importance of church reflected in speed of construction - enlarged chevet accommodated elaborate church ceremonies - tall vertical nature pulls eyes to ceiling and symbolically heaven -dark, mysterious interior increase spiritual feelings - stained glass enlivens interior surfaces - labyrinth-like nave; facilitates circumambulation of pilgrims	Chartres Cathedral
- Royal because jamb sculptures depict kings and queens from Old Testament; connection made between French and Biblical royalty - used by church hierarchy, no commoners - 19/24 statues survive - jamb statues stand in front of wall, almost fully rounded - upright, rigid, elongated figures reflect vertical columns behind and vertical nature of cathedral itself - rich courtly dress w/ vertical folds - robes almost hypnotic: concentric composition - heads: serenity; slightly heavy eyes; benevolent; humanized faces - heads lined up, but feet of different lengths - central tympanum: Christ as Judge of the World - three portals linked by lintels and 24 capitals that contain life of Christ	Royal Portals (from Chartres Cathedral)	

"Late medieval Europe. c. 1300-1325 CE. Painted wood. - used for private devotion - Christ pemaciated, drained of all blood, tissue, muscle; body distorted, stunted, stiff - horror of Crucifixion manifest - humanizing religious themes - grape-like drops of blood reference to Christ as ""mystical vineyard"" - Mary's face in expression of unbearable grief"	Röttgen Pietà	

** - Mary crowned as Queen of Heaven w/ Christ CHild in lap -
light as manifestation of divine; shades color patterns across grey stone of cathedral - part of lancet window - undamaged by fire of 194; reset w/ framing angles on either side of main scene - bands across surface typical of early Gothic stained glass	Notre Dame de la Belle Verrière (from Chartres Cathedral)
- eight medallions, format derives from stained glass windows - two vertical columns of four painted scenes - each scene w/ summary text of event depicted in roundel	Scenes from the Apocalypse (w/ Blanche of Castile)	

** Bibles moralisées.
Gothic Europe. c. 1225- 1245 CE.
Illuminated manuscript (ink, tempera, and gold leaf on vellum)
- moralized bible - top left: Blanche of Castile, mother and regent to king
  - top right: teenage King Louis IX
    - Louis and mother on thrones; oversized heads, emphasizing importance; framed by cityscapes; mom instructing (higher status) - bottom: older monk dictates to younger scribe; scribe outlining roundels seen on Scenes from the Apocalypse - luminosity of stained glass windows, strong black outlining of forms - modeling minimal	Blanche of Castile and Louis IX

** Late medieval Spain. 
c. 1320 CE. 
Illuminated manuscript (pigments and gold leaf on vellum). 
- illustrates story of Jewish exodus from Egypt under Moses and subsequent celebration - to be read at a Passover seder - fulfills Jewish requirement to tell story of Jews' escape from Egypt as reminder of God's mercy - narrative cycle of events form Books of Genesis and Exodus - this one used primarily at home; avoids more stringent restriction against holy images in a synagogue - generally most lavishly painted of Jewish manuscripts - two unknown artist (probably Christina); illustrated; Jewish scribe wrote Hebrew script - style similarities to 

** French Gothic manuscripts: handling of space, architecture, figure style, facial/gestural expression, medium - painted in Barcelona area of Spain 
- 56 miniatures using gold leaf background - read right to left according to manner of Hebrew texts	Golden Haggadah (The Plagues of Egypt, Scenes of Liberation, and Preparation for Passover)	
** Padua, Italy.
Unknown architect; Giotto di Bondone (artist). Chapel: 
c. 1303 CE; Fresco: c. 1305 CE. Brick (architecture) and fresco. - built over ancient Roman arena - also called Scrovegni Chapel after name of patron: Enrico Scrovegni - built to expiate sin of usury through which Scrovegni's father amassed a fortune - some narrative scenes illustrate Biblical episodes of ill-gotten gains	Arena (Scrovegni) Chapel

** - Christ as Judge,
coming at end of world - heavenly powers arranged in organized chorus; heads aligned in a row - twelve apostles arranged symmetrically around Christ - cross at bottom center divides saved from damned - on side of saved: Enrico Scrovegni as donor presenting model of church to angels - right: devil, who eats and excretes sinners - those guilty of usury/money-related sins (eg prostitution) particularly noted

** Last Judgement (from Arena (Scrovegni) Chapel)	
- scenes of Jesus's followers mourning death: usually scene contains Mary, St. John, and Mary Magdalene - St. John throws head back; Mary Magdalene cradles at Jesus's feet; Mary holds Jesus's head - left: Old Testament scene of Jonah being swallowed by whale and returning to life; parallel w/ New Testament scene of Christ dying and rising from the dead - shallow stage, figures occupy palpable space pushed forward toward picture plane - diagonal cliff formation points to main action daringly placed in lower left-hand corner - modeling indicated direction of light; light falls from above right - range of emotions: heavy sadness, quiet resignation, flaming outbursts, despair - sadness of scene emphasized by grieving angels, barrenness of tree - figures on lower left seen from back and isolate main action - clear foreground, middleground, and background - angels assemble in Heaven - two anonymous figures in back suggests space extends beyond	Lamentation (from Arena (Scrovegni) Chapel)	

** Basilica di Santa Croce. 
Florence, Italy. Filippo Brunelleschi (architect). c. 1429-1461 CE. Masonry. - rectangular chapel attached to church of Santa Croce, Florence - two barrel vaults on interior, small domes over crossing - interior w/ restrained sense of color, muted tones, punctuated by glazed terracotta tiles - Chapter House - attribution to Brunelleschi has be questioned - revival of classical columns and motifs - finished after death of Brunelleschi, so other architects made some parts (eg frame)	Pazzi Chapel	

* 1400's - 

** Florence, Italy. 
Leon Battista Alberti (architect). c. 1450 CE. Stone, masonry. - three horizontal floors of equal height separated by strongly articulated stringcourse - pilasters rise vertically and divide spaces into squarish shapes - strong classical cornice caps building - rejects rustication of earlier Renaissance palaces; instead uses beveled masonry joints - first floor pilasters Tuscan (derived from Doric); second are Alberti's own invention (derived from Ionic); third Corinthian - friezes contain Rucellai family symbols: billowing sails - square windows on first floor; windows w/ mullions on second and third floors - original building w/ five bays on left, w/ central door; second doorway bay and right bay added later; eighth bay fragmentary: owners of house next door refused to sell - patron: Giovanni Rucellai, wealthy merchant	Palazzo Rucellai	

** Fra Filippo Lippi. 
c. 1465 CE. Tempera on wood. - Mary seen as young mother - model may have been artist's lover - landscape inspired by Flemish painting; symbolic: rock formations indicate the Church; city near Madonna's head is Heavenly Jerusalem - motif of a pearl seen in headdress and pillow as products of the sea (in upper left corner); used in scenes of the Immaculate Conception of Mary and the Incarnation of Christ - depicted as if in a window in a Florentine home - humanization of a sacred theme - detailed drapery and halos

** Madonna and Child with Two Angels	
Sandro Botticelli. c. 1484-1486 CE. Tempera on canvas. - Venus emerges fully grown from foam of the sea; faraway look in eyes - roses scattered before her; created at the same time as Venus: love can be painful - left: zephyr (west wind) and chloris (nymph) - right: handmaiden ruses to clothe her - figures float, not anchored to ground - crisply drawn figures; pale colors - landscape flat and unrealistic, simple V-shaped waves - a Medici commission

** Birth of Venus	

** David
A: Donatello. 
*** D: c. 1440-1460 CE. 
M: Bronze. 
- first large bronze nude since antiquity - exaggerated contrapposto of body - life-size work probably meant to be housed in Medici Palace, not for public viewing - androgynous figure - stance: nonchalance, contemplating victory over Goliath; Goliath's head at David's feet; David's head lower to suggest humility - Laurel on hat: David was a poet; refers him as author of a book in Bible - nudity = refusal to wear armor?
** David	
Workshop of Robert Campin. 
1427-1432 CE. 
Oil on wood 
- left: donors, middle class kneeling before holy scene; wife added later, perhaps because of donor's marriage - center: Annunciation taking place in everyday Flemish interior - right: joseph in carpentry workshop; mousetrap represents capturing of the devil - humanization of traditional themes: no halos, domestic interiors, view into Flemish cityscape - symbolism: tower, lilies, and water stand for Mary's purity; water is baptism symbol; flowers have three buds, symbolizing the Trinity; unopened bud is unborn Jesus; Mary seated on floor: humility; Mary blocks fireplace (entrance to hell); candlestick: Mary holds Christ in womb; figure w/ cross comes in and through the window: the divine birth - meticulous handling of paint; intricate details - steeply rising ground line; figures too large for architecture they sit in
** Annunciation Triptych (Merode Altarpiece)	
*** A: "Jan van Eyck. 
**** D: c. 1434 CE. 
M: Oil on wood. 
- theories: wedding portrait of Giovanni Arnolfini and wife; memorial to a dead wife; betrothal; conferring legal and business privileges on his wife during an absence - symbols of weddings: custom of burning candle on first night; shoes cast off indicates they stand on holy ground; prayerful promising pose of groom; dog = fidelity - two witnesses in convex mirror; maybe artist himself; inscription: ""Jan van Eyck was here 1434"" - wife pulls up green dress to symbolize childbirth; not pregnant - statue of Saint Margaret, patron of childbirth, on bedpost - man is near window: role as someone who makes way into outside world; woman farther in room: role as homemaker - meticulous handling of paint; intricate details"
* 1500's  	
** Arnolfini Portrait	
*** A: Albrecht Dürer. 
**** D:1504 CE. Engraving. 
- influenced by classical sculpture; Adam looks like The Apollo Belvedere; Eve like Medici Venus - ideal image of humans before the Fall of Man - contrapposto of figures from Italian Renaissance - four humans in animals: cat (choleric/angry), rabbit (sanguine/energetic), elk (melancholic/sad), ox (phlegmatic/lethargic); kept in balance before Fall of Man - mouse represents Satan - Parrot symbol of cleverness - Adam tries to dissuade Eve; graphs mountain ash, which snakes hate - Northern European devotion to detailed paintings	Adam and Eve	

** "Matthias Grünewald. 
*** D:c. 1512-1516 CE. 
M: Oil on wood. 
- placed in monatery hospital where people were treated for ""Saint Anthony's Fire,"" ergotism--disease caused by eating fungus that grows on rye flour; causes convulsions and gangrene - St. Anthony's Fire explains presence of St. Anthony on first and third views - first view: Crucifixion: dark background; dead, decomposing flesh; arms almost torn from sockets; lashed and whipped body; agony of body unflinchingly shown; symbolizes agony of ergotism; swooning Mary dressed like nuns who worked in the hospital; when panels open to reveal next scene, Christ amputated as patients suffering ergotism would be; same in predella: Christ's legs seem amputated below kneecaps - second view: Marian symbols: enclosed garden, closed gate, rosebush, rosary; Christ rises from dead on right--rags changed to glorious robes, showing wounds, which don't harm him now; message to patients: earthly diseases will vanish in next world - third view: symbols of ergotism: oozing boils, withered arm, distended stomach (not illustrated) - believed to have healing powers when looked upon - no landscape or perspective"

** Isenheim Altarpiece	
A: Lucas Cranach the Elder. 
*** D:c. 1530 CE. Woodcut and letterpress. 
- done in consultation w/ Martin Luther - left: Last Judgement; Moses holds Ten Commandments, represents Old Law, Catholicism; Law of Moses not enough to live a good life; skeleton chases person into hell - right: figure bathed in Christ's blood; faith in Christ alone is needed for salvation
** Allegory of Law and Grace	
*** A: Pieter Bruegel the Elder.
**** D: 1565 CE.
***** M: Oil on wood.
 - one of series of paintings representing the months: this is November/December - alpine landscape, winter scene - strong diagonals lead eye deeper into painting - figures peasant types, not individuals - high horizon line - many details; nothing static - hunters had little success in winter hunt; dogs skinny and hang their heads - atmospheric perspective	
**  Hunters in the Snow	
*** A: "Leonardo da Vinci.
**** D:  c. 1494-1498 CE. 
***** M: O and tempera - 
commissioned by the Sforza of Milan for the refectory (dining hall) of a Dominican abbey - relationship between the friars eating and a Biblical meal - only Leonardo work remaining in situ - linear perspective; orthogonals of ceiling and floor points to Jesus - apostles in groupings of three; Jesus alone but before a group of three windows that symbolize the Trinity - experimental combination of paints to yield greater chiaroscuro; paints gean to peel off wall in Leonardo's lifetime and has been restored many times - great drama of the moment: Jesus says, ""One of you will betray me"" - various reactions on faces of apostles; anguish on face of Jesus - Judas falls back clutching bag of coins, face in darkness"	
** The Last Supper	
*** Vatican City,
****  Italy. 
***** Michelangelo. 
Ceiling frescoes: 
c. 1508-1512 CE; altar frescoes: 
c. 1536-1541 CE. Fresco. - 

** Sistine Chapel 
erected in 1472 and painted by quattrocento masters, including Botticelli and Perugino, as well as Michelangelo's teach Ghirlandaio - function of chapel: place where new popes are elected - complicated arrangement of figures for ceiling, broadly illustrating first few chapters of Genesis, w/ accompanying Old Testament figures and antique sibyls--based on antique sculptures - three hundred figures on ceiling, no two in same pose; Michelangelo's lifelong preoccupation w/ male nude in motion - enormous variety of expression - painted cornices frame groupings of figures in highly organized way - many figures (ie the Ignudi) are done for artistic expression > enhance narrative - acorns motif on ceiling, inspired by crest of patron, Pope Julius II
Sistine Chapel Ceiling	
** - one of five sibyls on ceiling - wears Greek style turban - turns head, as if listening - expression seems sorrowful - contrapposto - holds scroll containing her prophecy - combination of Christian religious and pagan mythological imagery	Delphic Sibyl (from Sistine Chapel)	
- few remaining survivors cling to mountain tops - man carrying drowned son to safety, will only meet his son's fate - over 60 figures; crowded composition - sculptural intensity of figure style - ark in background only safe haven	The Flood (from Sistine Chapel)	
- in contrast to ceiling, no cornice divisions; one large space w/ figures more casually grouped - mannerism in distortions of body, elongations, crowded groups - four broad horizontal bands act as unifying element: (1) bottom: left: dead rising, right: mouth of hell (2) second level: ascending elect, descending sinners, trumpeting angels (3) third level: those rising to heaven gathered around Jesus (4) top lunettes: angels carrying the Cross and the Column, instruments used at Christ's death - Christ in center and gestures defiantly w/ right hand; complex pose - justice deliver: good rise, evil fall - lower right-hand corner has figures from Dante's Inferno: Minos and Charon - St Bartholomew's face modeled on a contemporary critic; St Bartholomew holds his skin, symbol of his martyrdom, but the skin's faceis Michelangelo's; oblique remark about critics who skin him alive w/ criticism - spiraling composition reaction against High Renaissance harmony of Sistine Chapel ceiling; reflects disunity of Christendom caused by Reformation	Last Judgement (from Sistine Chapel)	
"Vatican City, Italy. Michelangelo. Ceiling frescoes: c. 1508-1512 CE; altar frescoes: c. 1536-1541 CE. Fresco. - commissioned by Pope Julius II to decorate his library - originally called ""Philosophy"" because pope's philosophy books meant to be housed on shelving below - one painting in complex program of works that illustrates vastness and variety of papal library - open, clear light uniformly spread throughout composition - nobility and monumentality of forms parallel to greatness of figures represented; figures gesture to indicate philosophical thought - building behind might reflect Bramante's plan for Saint Peter's - center: plato (w/ features of Leonardo on left, pointing up) and Aristotle - Bramante, Pope's architect, bald figure of Euclid on lower right - Raphael in corner at extreme right - Michelangelo resting on stone block, writing a poem - overall composition influenced by Leonardo's The Last Supper"
** School of Athens	
Titian.
c. 1538 CE.
Oil on canvas.
81. Frontispiece of the Codex Mendoza. Viceroyalty - may not have been a Venus; may have been a courtesan - sensuous delight in skin tones - looks at viewer directly - complex spatial environment: figure placed forward on picture plane, servants in middle space; open window w/ paints in background - roses contribute to floral motif carried throughout - dog = faithfulness? - cassoni - patron Guidobaldo della Rovere of Urbino - painting became standard for future reclining female nudes	Venus of Urbino	
** Viceroyalty of New Spain.
c. 1541-1542 CE.
Ink and color on paper
- named after Antonio de Mendoza, viceroy of New Spain - intended as a history of the Aztecs for Charles V of Holy Roman Empire - created 20 years after Spanish conquest - shows Aztec rulers and daily life in Mexico - uses pictograms created by Aztec artists that were later annotated in Spanish - depicted founding of Tenochtitlan and conquest of Colhuacan and Tenayucan on bottom - enemy temples on fire while Aztec warriors carry clubs and shields - small representation of Temple Mayor above eagle - skulls represent sacrificial victims - eagle landing on a cactus at intersection of two waterways commemorates division of Tenochtitlan into four quarters - current Mexican flag has eagle perched on a cactus that rests on a rock, as seen in here	Frontispiece of the Codex Mendoza
***  Oil on canvas. 
- angel depicted w/ arquebus (a form of rifle) instead of traditional sword - military poses derived from European engravings of military exercises - probably one in a series of angel drummers, buglers, standard bearers, and holders of swords - drapery of a 17th century Spanish aristocrat; rich costuming - mannerist influence in stiffness of figure; dance-like pose - Latin inscription: ""Asiel, fear of God"" - angel appears in androgynous stance - gold embroidered on fabric favored by indigenous people - may have originated in region around Lake Titicaca in Collao region of Peru"	Angel with Arquebus, Asiel Timor Dei	
Circle of the González Family. 
** c. 1697-1701 CE. 
Tempera and resin on wood, shell inlay. - commissioned by Jose Sarmiento de Valladares, viceroy of New Spain - displayed in Viceregal Palace in Mexico City - only known example of art work that combines biombos and enconchados - two faces of screen: hunting scene and war scene - hunting scene suited to intimate space for small receptions - war scene more suited for grander room w/ political importance - war scene depicts contemporary event of the Great Turkish War 1683-1699; Dutch print used for inspiration - illustrates a scene of Habsburg power	Screen with the Siege of Belgrade and Hunting Scenes	
"Miguel González. c. 1698 CE. Based on original Virgin of Guadalupe. Basilica of Guadalupe, Mexico City. 16th century CE. Oil on canvas on wood, inlaid with mother-of-pearl. - painting describes event where Mary appeared to Native Americans on a hill called Tepeyac, a shrine sacred to a pre-Columbian goddess - Mary ordered a Native American convert, Juan Diego in 1531, to tell the local archbishop to build a sanctuary on this site - Mary made the hilltop flower and Juan Diego brought the flowers to the archbishop; Juan Diego's cloth revealed the Virgin's image - Virgin of Guadalupe most revered symbol in Mexico; patroness of New Spain - symbol of Mexico: eagle perched on cactus at bottom center - in Guadalupe images Mary always stands on a crescent moon; surrounded by sun rays; clouds behind - Revelations 12:1: ""A great sign appeared in heaven: a woman clothed with the sun, with the moon under her feet and a crown of twelve stars on her head"" - surrounded by four roundels depicting apparition to Juan Diego at moment Virgin's image is revealed in his tunic - brocade Virgin's robes made of enconchados (influence of Asian decorative arts) - image in demand: many made for export around New Spain"	
** The Virgin of Guadalupe (Virgen de Guadalupe)	
A: Attributed to Juan Rodríguez Juárez.
D: c. 1715 CE. 
M: Oil on canvas. 
- panel from first known series of casta paintings; may not have been a completed set - Spanish social hierarchy w/ European ancestry at top; sixteen different gradations of social scale - Spanish blood linked to civilizing forces; waring lavish costumes - Africans and Indians rendered w/ respect; showing harmony and mixing of classes - many Africans and Indians rendered w/ South European features: slim noses, curly hair, almond-shaped eyes - Spanish colonists commissioned w/ works to be sent abroad to show how caste system of New World works - not considered art objects but illustrations of ethnic groups	Spaniard and Indian Produce a Mestizo	
** Jacopo da Pontormo.
*** D: 1525-1528 CE.
**** M:Oil on wood
- center of circular composition: grouping of hands - elongation of bodies - high-keyed colors; taking into account darkness of the chapel placed in? - no ground line for many figures; what is Mary sitting on? - hands seem disembodied - some androgynous figures - no weeping, just yearning - linear bodies twisting around one another - anti-classical composition - no tomb, just carrying of Jesus's lifeless body	Entombment of Christ
Rome, Italy. Giacomo da Vignola, plan (architect); Giacomo della Porta, facade (architect); Giovanni Battista Gaulli, ceiling fresco (artist). Church: 16th century CE; facade: 1568-1584 CE; fresco and stucco figures: 1676-1679 CE. Brick, marble, fresco, and stucco. - principal church of Jesuit order - column groupings emphasize central doorway - tympanum and pediment over central door - slight crescendo of forms toward center - two stories separated by cornice; united by scrolls - framing niche acts as unifying device - interior has no aisles, meant for grand ceremonies	
** Il Gesù Facade	
- originally dedicated to Saint Paul - rededicated to Virgin Mary in gratitude for military victory in Bohemia in 1620 - Turkish standards captured in Siege of Vienna in 1683 on display - single wide nave; one of side chapels houses Bernini's Ecstasy of Saint Teresa - first story: six Ionic pilasters; emphasis placed on center of facade - round and triangular pediments; broken pediments; swags and scrollwork	
Santa Maria della Vittoria (from Ecstasy of Saint Teresa)	
Rome, Italy. Francesco Borromini (architect). 1638-1646 CE. Stone and stucco. - named so because on square in Rome w/ four fountains - unusually small site - alternating convex and concave patterns and undulating volumes in ground plan and facade - facade higher than rest of building - interior side chapels merge into central space - interior dome oval shaped and coffered - walls treated sculpturally - shades of white; avoided colors used in many Baroque buildings	San Carlo alle Quattro Fontane	
"Versailles, France. Louis Le Vau and Jules Hardouin-Mansart (architects). Begun 1669 CE. Masonry, stone, wood, iron, and gold leaf (architecture); marble and bronze (sculpture); gardens. - reorganization and remodeling of hunting lodge into elaborate place - center of building was Louis XIV's bedroom, or audience chamber, from which all aspects of design radiate like rays from the sun (""the Sun King"") - corresponds to Louis XIV's political and economic ambitions - building centered in vast garden and town complex radiating from - subdued exterior decoration on facade; undulation of projecting members is understated - Hall of Mirrors: 240 feet long; barrel-vaulted painted ceiling; light comes in from one side and ricochets off largest panes of glass that could be made at the time; flickering use of light in architectural setting; ceiling paintings illustrate civil and military achievements of Louis XIV - Gardens: classically and harmoniously arranged; formal gardens near palace; more wooded and less elaborate paintings at distances farther away; Baroque characteristics: size, long vistas, terminal views in fountains and statuary; mile-long canal crossed by another canal forms main axis of gardens; only fountains near palace played all the time; others turned on for the king if he walked through the gardens"	
** The Palace at Versailles	
Cornaro Chapel, Church of Santa Maria della Vittoria. Rome, Italy. Gian Lorenzo Bernini. c. 1647-1652 CE. Marble (sculpture); stucco and gilt bronze (chapel). - sculptural interpretation of Saint Teresa's diary where she tells of her visions of God, many involving an angel descending w/ arrow and plunging it into her - natural light redirected onto sculpture from window hidden above - marble handed to reveal textures: skin is high gloss, feathers of an angel are rougher, drapery animated and fluid, clouds roughly cut - carved from single block of marble - figures seem to float in their space, w/ rays of God's light symbolically illuminating scene from behind - Saint Teresa's pose suggests sexual exhaustion, feeling consistent w/ her description of spiritual ecstasy in diary entries - stagelike setting w/ patrons, members of Carnaro family, sitting in theatre boxes looking on and commenting	
** Ecstasy of Saint Teresa	
Caravaggio. c. 1597-1601 CE. Oil on canvas. - one of three paintings illustrating life of Saint Matthew in chapel dedicated to him by Cantarelli family - light comes in from two sources on right, creating a tenebroso effect on figures - diagonal shaft of light points directly to Saint Matthew, who points to himself as if unsure that Christ would select a tax collector, depicting a moment in time - Christ's hand gesture similar to Adam's on Sistine Chapel ceiling - Foppishly dressed figures in latest Baroque fashion - narrow stage for figures to sit and stand on - only slight suggestion of halo on Christ's head indicates sanctity of scene - sensual figures, everyday characteristics - naturalist approach to the Baroque	
** Calling of Saint Matthew	
"- on ceiling in main nave of Il Gesu, Rome - monogram of Jesus's ""IHS"" in brilliantly lit sea of golden color - figures tumbling below name; some carved in stucco, enhancing 3D effect - some cast long shadows across barrel vault - some painted figures no stucco, but maintain vibrant 3D illusion - as if ceiling were open to sky and figures spiraling around Jesus's name - di sotto in su - damned cast into hell; saved rise heavenward; a Last Judgement - influence of Bernini's dramatic emotionalism in the style; Gaulli was Bernini's pupil"	Triumph of the Name of Jesus (from Il Gesù)	
Diego Velázquez. c. 1656 CE. Oil on canvas. - group portrait of artist in studio at work; steps back from canvas and looks at viewer - Velazquez wears cross of the Royal Order of Santiago, elevating him to knighthood - central: Infanta Margarita of Spain with her meninas (attendants), a dog, a dwarf, and a midget - behind: two chaperones in half-shadow - doorway: Jose Nieto? head of queen's tapestry works (hence his hand on a curtain) - king and queen appear in a mirror; what's the mirror reflecting? canvas? painting? - alternating darks and lights draw us deeper into canvas; mirror simultaneous reflects out into our space - dappled effect of light on shimmering surfaces - painting originally hung in Philip IV's study	
** Las Meninas	
Peter Paul Rubens. 1621-1625 CE. Oil on canvas. GENERAL - heroic gestures, demonstrative spiraling figures - mellow intensity of color, inspired by Titian and Caravaggio - sumptuous full-fleshed women - 21 historical paintings allegorically retelling life of Marie de'Medici, Queen of France, wife of Henry IV - splendid costumes suggest opulent theatrical production - allegories assist in telling story and mix freely w/ historical people  SPECIFIC - Henry IV smitten by portrait of intended, held by Cupid (god of love) and Hymen (god of marriage) - Jupiter and Juno look down; symbolic of marital harmony; they express support - royalty considered demigods; approval of mythological gods in concert w/ their beliefs about themselves - portraits exchanged before the marriage - married by proxy in 1600 - behind Henry: personification of France: female figure w/ masculine helmet and manly legs; whispers to Henry to take love over war	Henri IV Receives the Portrait of Marie de'Medici	
** Rembrandt van Rijn. 
*** 1636 CE.
**** Etching.
- only image of Rembrandt w/ wife in an etching - 30 year old Rembrandt w/ new bride - not wearing contemporary dress; fanciful dress - images of Saskia abundant in Rembrandt's output, source of inspiration - martial harmony, Saskia as a muse inspiring him - wife and mother of four - Rembrandt drawing/etching - painted 50 self-portraits; 32 self-portrait etchings; 7 self-portrait drawings - not for general sales; private purposes	Self-Portrait with Saskia	
Johannes Vermeer. c. 1664 CE. Oil on canvas. - small number of Vermeer works in existence - except for two landscapes, works portray intimate scenes in interior of Dutch homes - viewer looks into private world with seemingly small gestures take on [significance greater than what first appears] - woman seem unaware of viewers' presence - light enters from the left and warmly highlights textures and surfaces: garments, wood table, marble checkerboard floor, jewelry, painting, etc. - moment in time: stillness and timelessness - moment of weighing and judging - behind: painting of the Last Judgement, time of weighing souls - balance has nothing in it; pearls and coins on table waiting to be measured - balancing reference perhaps to unborn child - allegory - vanitas: gold should not be a false allure - geometric lines focus on central point at pivot of balance - dressed in fine clothing: fur-trimmed - maybe a Vermeer family member posed for painting; theories that it may have been his wife, Caterina	Woman Holding a Balance	
Rachel Ruysch. 1711 CE. Oil on wood. - contruct of perfect specimens all in bloom at same time - asymmetrical/artful arrangement - probably used illustrations in botany textbooks as basis for painting - in a phase where artist produced still lifes in a woodland setting	Fruits and Insects	
Conques, France. Romanesque Europe. Church: c. 1050-1130 CE; Reliquary of Saint Foy: ninth century CE, with later additions. Stone (architecture); stone and paint (tympanum); gold, silver, gemstones, and enamel over wood (reliquary). - built along pilgrimage road to Santiago de Compostela - build to handle large number of pilgrims; wide transepts, large ambulatory w/ radiating chapels - massive heavy interior walls, unadorned - no clerestory; light provided by windows over side aisles and galleries - barrel vaults in nave, reinforced by transverse arches - cross-like ground plan	Church of Sainte-Foy	
"- largest Romanesque tympanum - Christ as strict judge, dividing world into those going to Heaven and those going to Hell - Christ's welcoming right hand, cast down left hand - dividing line runs vertically through cross in middle of composition - archangel Michael and devil at Chris's feet, weighing the souls -Hell w/ damned on right; saved on left; people enter church on right and exit saved, on left - subject reminds pilgrims of point of pilgrimage - 124 figures originally richly painted, densely packed together - saved moe towards Christ, Mary, and Saint Peter in lead - paradise, on lower level, portrayed as heavenly Jerusalem - left triangle: arches of Conques Abbey w/ dangling chains: Sainte Foy interceded for those enslaved by Muslims in Spain; she herself kneeling before giant hand of God - lower right level: devil presides over chaotic tangle of tortured condemned sinners - inscription on lintel: ""O Sinners, change your morals before you might face a cruel judgement"""	
** Last Judgement (from Church of Sainte-Foy)	
- reliquary of young girl martyred in early fourth century; refused to sacrifice to Roman gods in pagan ritual - relics of body stolen from nearby town and enthroned in Conques in 866 - one of earliest large scale sculptures in Middle Ages - jewels, gems, crown added over the years by faithful - child's skull housed in mannish looking enlarged head	Reliquary of Sainte-Foy (from Church of Sainte-Foy)	
Romanesque Europe (English or Norman). c. 1066-1080 CE. Embroidery on linen. - actually embroidery - commissioned by Bishop Odo, half-brother of William the Conqueror - story (in Latine) of William's conquest of England in Battle of Hastings in 1066 and after - probably designed by man, executed by women - fanciful beasts in upper and lower registers - borders sometimes comment on main scenes, or show scenes of everyday life - color used in non-natural manner; different parts of horse colored variously - neutral background - flatness of figures; no shadows - narrative tradition going back to Column of Trajan - 75 scenes, over 600 people - 230-feet long; continues narrative tradition on Medieval art - uncertainty over how this work was meant to be displayed - stylized and elongated everything - last scene lost; probably William's crowning	Bayeux Tapestry	
Early medieval Europe. Mid-sixth century CE. Silver gilt worked in filigree, with inlays of garnets and other stones. - cloisonné and chasing techniques - zoomorphic elements - small + portable - decline of classical tradition - probably owned by rich Merovingian woman; meant to go w/ her to afterlife - fish below center of each pin - all surfaces covered; decorations adjust to shape	Merovingian looped fibula	

"Early medieval (Hiberno Saxon) Europe. c. 700 CE. Illuminated manuscript (ink, pigments, and gold on vellum). - written by Eadrith, bishop of Lindisfarne - unusual: made by one person, not a team - Latin w/ annotations in English between lines; English added around 970, called Anglo-Saxon miniscule - one of oldest surviving manuscript of Bible in English - uses Saint Jerome's translation of the Bible: ""The Vulgate"" - 130 calf skins used - colophon discusses making of"	Lindisfarne Gospels	
- cross depicted on page filled w/ horror vacui decoration - dog-headed snakes intermix w/ birds w/ long beaks - cloisonné style used in bodies of birds - elongated figures lost in maze of S shapes - symmetrical arrangement - black background makes patterning stand out - mixture of traditional Celtic imagery and Christian theology	Cross Page from the Book of Matthew (from Lindisfarne Gospels)	
"- traditional symbol associated w/ St. Luke: calf (sacrificial animal) - identity of calf acknowledged w/ ""imago vituli"" - St. Luke identified by Greek words using Latin characters: ""Hagios Lucas"" - heavily bearded Saint Luke gives weight to authority as author, but appears younger man - sits w/ legs crossed holding scroll and writing instrument - writing his gospels"	Saint Luke Portrait (from Lindisfarne Gospels)	
"- ""incipit"": opening words of Saint Luke's gospel: ""Quoniam Quidem ..."" - numerous Celtic spiral ornaments; step patterns appear in enlarged O - lower right corner: naturalistic detail of cat who has eaten eight birds"	Saint Luke Incipit Page (from Lindisfarne Gospels)	
Córdoba, Spain. Umayyad. c. 785-786 CE. Stone masonry. - doubled arched columns, brilliantly articulated in alternating bands of color; voussoirs - light and airy interior - horseshoe-shaped arches traditional in Visigothic Spain and Roman architecture - hypostyle mosque; no central focus, no congregational worship - original wooden ceiling replaced by vaulting - complex dome over mihrab w/ elaborate squinches - columns spolia from ancient Roman structures - relatively short columns made ceilings low; doubling of arches enhances interior space; perhaps influenced by Roman aqueduct in Merida, Spain - kufic calligraphy on walls - built on site of church; after Christian reconquest center of mosque used for church	Great Mosque	
Umayyad. c. 968 CE. Ivory - calligraphic inscription in Arabic identifies owner, asks for Allah's blessings, and tells function - container for expensive aromatics - gift for caliph's younger son, most likely as a coming-of-age gift - ivory objects given as gifts to members of royal family at important time in their life - horror vacui - vegetal and geometric motifs - eight medallion scenes showing pleasure activities of royal court: hunting, falconry, sports, musicians - from Muslim Spain	Pyxis of al-Mughira	
** The Tête à Tête from Marriage à-la-mode	
*** William Hogarth.
**** c. 1743 CE.
*****  Oil on canvas.
- one of six scenes in suite of paintings - narrative paintings; later turned into series of prints - highly satiric paintings about aristocratic English society and those who would like to buy their way into it - shortly after marriage, each partner has been pursuing pleasures without the other: husband has been out all night w/ another woman (dog sniffs suspiciously at another bonnet); broken sword means he has been in a fight and probably lost (may also be a symbol for sexual inadequacy); wife has ben playing cards all night, steward (at left) indicating by his expression that she has lost a fortune at whist (he holds nine unpaid bills in his hand, one was paid by mistake); turned-over chair indicates violin player made hasty retreat when husband came home	
** Granada, Spain. Nasrid Dynasty. 1354-1391 CE. Whitewashed adobe stucco, wood, tile, paint, and gilding. - palace of Nasrid sultans of Southern Spain; preserved by Christians to commemorate victory - light, airy interiors; fortress-like exterior - built on hill overlooking city of Granada - contains palaces, gradens, water pools, fountains, courtyards - small, low bubbling fountains in each room to provide cool temperatures in summer	Alhambra	
- thin columns support heavy roofs; feeling of weightlessness - intricately patterned and sculpted ceilings and walls - central fountain supported by protective lions; animal imagery permitting in secular monuments - part of walls chiseled through to create vibrant light patterns within	Court of the Lions (from Alhambra)	
- sixteen windows at top; light dissolves into honeycomb of stalactites that dangle from ceiling (simulate heavens; good acoustics) - abstract patterns, abstraction of forms - 5000 muqarnas refract light; carved in stucco onto ceiling - highly sophisticated and refined interior - perhaps used as a music room or for receptions	Hall of the Sisters (from Alhambra)	
** Edirne,
Turkey. Sinan (architect).
1568-1575 CE.
Brick and stone.
- extremely thin soaring minarets - abundant window space makes for brilliantly lit interior - decorative display of mosaic and tile work - inspired by Hagia Sophia, but centrally planned - octagonal interior, w/ 8 pillars resting on square set of walls - open airy interior contrasts w/ conventional mosques that have partitioned interiors - part of complex including hospital, school, library, etc. - Sinan chief court architect for Suleiman the Magnificent - transitions from square ground plan to round dome achieved by inserting smaller domes into corners - huge piers support dome	Mosque of Selim II	
** Henri Matisse.
1912 CE.
Oil on canvas.
- still life painting - violent contrasts of color - thinly applied colors; white of canvas shows through - energetic painterly brushwork - may have been influenced by decorative quality of Asian art - broad patches of color anticipate Color-Field painting later in century	Goldfish	
** "Vassily Kandinsky.
1912 CE.
Oil on canvas
- movement toward abstraction; representational objects suggested rather than depicted - title derived from musical compositions strongly articulated use of black lines - colors seem to shade around line forms - felt that sound and color were linked; Kandinsky generally believed to have synesthesia - gave musical titles to works like ""Composition"" and ""Improvisation"" - wanted viewer to respond to a painting the way one would to an abstract musical composition like a concerto, sonata, or symphony"	Improvisation 28 (second version)	
** "Ernst Ludwig Kirchner. 1915 CE. Oil on canvas. - 
""unwilling volunteer"" driver in the artillery in WWI, rather than be drafted into infantry - declared unfit for service; lung problems and weakness; mental breakdown-scholarly debate whether or not faked to avoid service - painted during recuperation period - drawn face; loss of right hand indicates his feeling that he has an inability to paint - nude model represents what he used to paint, but no longer can - nightmarish quality - colors not representational, but symbolic and chosen to provide jarring impact - expressive quality of horrified facial features and grim surroundings - titled perspective moves things closer to the picture plane - life plagues by drug abuse, alcoholism, then paralysis"	Self-Portrait as a Soldier	
** Käthe Kollwitz. 1919-1920 CE. Woodcut. 
- themes of war and poverty dominate her works - themes of women grieving over dead children; her son died in WWI, then she became a socialist - Karl Liebknecht among the founders of the Berlin Spartacus League that became the German Communist Party - 1919: Liebknecht shot to death during a Communist uprising in Berlin called the Spartacus Revolt - no political reference in woodcut - human grief dominates - stark black and white of woodcuts to magnify grief	
** Memorial Sheet for Karl Liebknecht	
Pablo Picasso. 1907 CE. Oil on canvas. - first Cubist work, influenced by late Cezanne and African masks - represents five prostitutes in a bordello on Avignon Street in Barcelona, each posing for a customer - poses not traditionally alluring but awkward, expressionless, and uninviting - three on left more conservatively painted, two on right more radical; reflects dichotomy in Picasso - multiple views expressed at the same time - no real depth - influenced by Gauguin's primitivism	Les Demoiselles d'Avignon	
** Georges Braque. 1911 CE. Oil on canvas. 
- Analytical Cubism; worked in concert w/ Picasso to develop this style - rejected naturalistic and conventional painting - fractured forms; breaking down objects into smaller forms - clear-edged surfaces sit on picture plane, not recessed in space - nearly monochrome - not portrait of Portuguese musician; exploration of shapes - only realistic elements: stenciled letters and numbers; suggest dance hall poster behind guitarist? - cafe atmosphere	
** The Portuguese	
Constantin Brancusi.
Original
1907-1908 CE.
Stone. -
symbolic, almost Cubist, rendering of male and female bodies - intertwined and enveloped figures - two eyes become one, almost Cyclops-like - interlocked bodies - Brancusi worked in Rodin's studio - fourth stone version of this subject, done as a commission; first was one of Brancusi's earliest efforts at stone carving; second, a plaster cast, exhibited at the Armory Show; third used as tombstone in Montparnasse Cemetery in Paris over the body of a suicide victim: young Russian anarchist (artist asked by a friend of the deceased, who had jilted her, for a marking of her grave; artist said take what you want; he took this); there may have been many more undocumented versions	The Kiss	
** Alfred Stieglitz. 1907 CE. Photogravure.
 - photographed the world as he saw it, arranged little and allowed people and events to make their own compositions - interested in compositional possibilities of diagonals and lines acting as framing elements - diagonals and raming effects of ladders, sails, steam pipes, etc. - depicted poorest passengers on a ship traveling from the US to Europe in 1907; some may have been people turned away from entrance to the US, more likely artisans whose visas had expired and were returning home - published in October 1911 in Camera Work - influenced by experimental European painting; compared to Busist drawing by Picasso; Cubist-like in arrangement of shapes and tonal values - represents social divisions of society - steerage: the part of a ship reserved for passengers w/ the cheapest tickets	The Steerage	
** Fountain
*** "Marcel Duchamp. 
**** 1950 CE. (original 1917). 
Readymade glazed sanitary china with black paint.
- ready-made, actually a found object Duchamp deemed to be a work of art - entered in an unjuried show for the Society of Independent Artists (which he was a part of) under a different name; ""accepted"" but hid during the exhibition; resigned afterward - signed by ""artist"" R. Mutt, a pun on Mutt and Jeff comic strip and Mott Iron Works - title Fountain a pun; fountains spout liquid, a urinal meant to collect; added irony placing urinal upside down"
** Object (Le Petite-Déjeuner en Fourrure)	
*** Meret Oppenheim.
**** 1936 CE.
Fur-covered cup, saucer, and spoon. - done in response to Picasso's claim that anything looks good in fur; went to store right after meeting to buy materials - combination of unlike objects: fur-covered teacup, saucer, and spoon - erotic overtones - assemblage - combined traditionally female and genteel objects vs. masculinity of sculpture done in hard surfaces in great scale and made vertically - chosen by visitors of a Surrealist show in New York as the quintessential Surrealist work of art - fame came young (22 when she made it) and inhibited growth as an artist
** The Two Fridas	
*** Frida Kahlo.
**** 1939 CE.
***** Oil on canvas.
- juxtaposition of two self-portraits - left: Kahlo dressed as a Spanish lady in white lace - right: Kahlo dressed as a Mexican peasant; stiffness and provincial quality of Mexican folk art serves as direct inspiration for artist - two hearts twined together by veins cut by scissors at one end and lead to portrait of husband, Rivera at other; painted at time of divorce - barren landscape, two figures sit against wildly active sky - rejected label of Surrealism - vine acts as an umbilical cord, symbolically associating Rivera as husband and son - blood on lap suggests many abortions and miscarriages, also her surgeries related to her polio
***** "Wifredo Lam. 
1943 CE. 
Gouache on paper mounted on canvas. 
- Cuban-born artist whose career took him to Europe and US - interested in Cuba's mixture of Hispanic and African cultures - influenced by African sculpture; Cubist works; Surrealist paintings (member of Surrealist movement in Paris) - ""intended to communicate a psychic state"" - addresses history of slavery in colonial Cuba - crescent-shaped faces suggest African masks - rounded backs, thin arms and legs, pronounced hands and feet - meant to suggest sugarcane, which are grown in field, not jungles"
** The Jungle	
*** Varvara Stepanova. 
**** 1932 CE. 
Photomontage. 
- one of main figures in Russian avant-garde movement - graphic art for political and propaganda purposes - influenced by Cubism and Futurism - five year plan: Soviet practice of increasing agricultural and industrial output in five years; launched in 1928; considered complete in 1932 - emphasis on growth of heavy industry rather than consumer goods - hugs increases in electrical output (dominant industrial symbol in work) - double page spread in a book - red dominates: color of Communist Soviet Union - CCCP Russian abbreviation for the Soviet Union - large portrait of Lenin dominates; although deceased, his image is used to stimulate patriotism	Illustration from The Results of the First Five-Year Plan	
**  Piet Mondrian. 1930 CE. Oil on canvas. 
- only primary colors used - severe geometry of form, only right angles; gridlike forms - no shading of colors - asymmetrical composition	Composition with Red, Blue and Yellow	
Pennsylvania, 
U.S. Frank Lloyd Wright (architect). 
1936-1939 CE. 
Reinforced concrete, sandstone, steel, and glass. 
- cantilevered porches extend over waterfall; accent on horizontal lines; architecture in harmony w/ site - living room contains glass curtain wall around 3/4 sides; embraces woods around - floor of living room and walls of building made from stone of the area - hearth is center of house, an outcropping of natural stones surrounds it - suppression of space devoted to hanging a painting; Wright wanted architecture to dominate - irregularity and complexity of ground plan and design	
** Fallingwater	
Poissy-sur-Seine, France. Le Corbusier (architect). 
1929 CE. 
Steel and reinforced concrete. 
- three bedroom villa w/ servant's quarters - boxlike horizontal quality; abstraction of a house - main part lifted off ground by narrow pilotis; house appears to float on them - turning circle on bottom floor a carport, so that family members can enter directly from car - all space utilized, including roof (patio) - no historical ornamentation - subtle colors: white on exterior symbolized modern cleanliness, the new, simplicity, healthful living - open interior free of many walls - furniture build into walls - ribbon windows wind around second floor - streamlined look - living spaces around open courtyard-type setting on second floor; surrounded by glass - patrons: Pierre Emilie Savoye, wanted a country house	
** Villa Savoye	
"New York City, U.S. Ludwig Mies van der Rohe and Philip Johnson (architects). 1954-1958 CE. Steel frame with glass curtain wall and bronze. - reflection of Minimalist movement in painting - ""less is more"" can be seen in this building: great simplicity, geometry of design, elegance of construction - set back from street on wide plaza balanced by reflecting pools - bronze veneer gives skyscraper monolithic look - interplay of vertical and horizontal accents - steel-and-glass skyscraper became the model after WWI - triumph of International Style"	
** Seagram Building	
Jacob Lawrence. 
1940-1941 CE.
 Casein tempera on hardboard. 
- series of 60 paintings depicting migration of African-Americans from rural south to urban North after WWI - overall color unity in series unites each painting - forms hover in large spaces - flat simple shapes - unmodulated colors - collective African-American experience, little individuality to figures - goes back to tempera paint; influenced by Italian masters of 14th and 15th centuries - collective unity achieved by painting one color across many panels before going on to next color - angularity of forms - scene involved public restaurant in North; segregation emphasized by yellow poles that zigzag down center - titled table tops show surface of table - narrative painting in an era of increasing abstraction	The Migration of the Negro, Panel no. 49	
** "Diego Rivera. 1947-1948 CE. Fresco. - 50 x 13 feet - 
originally in lobby of Hotel Del Prado - 
after 1985 earthquake that destabilized hotel, placed in Alameda Park, Mexico City's first city park; build on grounds of Aztec marketplace - three ears of Mexican history depicted: conquest and colonization of Mexico by Spanish; Porfirio Diaz dictatorship; revolution of 1910 - depicts a who's who of Mexican politics, culture, and leadership: Sor Juana; Benito Juarez, five term president; General Santa Ana handing the Keys of Mexico to General Winfield Scott; Emperor Maximilian and Empress Carlota; Jose Marti, father of Mexican independence (tipping hat); General Porfirio Diaz w/ medals, asleep; police officer ordering a family out of an elitist park; Francisco Madero, martyred president; artist at center, age ten, holding hands with Caterina (""Death"") dreaming of a perfect love, w/ Kahlo behind - horror vacui; didactic; colorful - revival of fresco painting, a Mexican specialty"	Dream of a Sunday Afternoon in the Alameda Park	
** Willem de Kooning. 
1950-1952 CE. Oil on canvas. 
- ferocious woman w/ great fierce teeth and huge eyes - large bulbous breasts satire on women who appear in magazine ads; smile said to be influenced by ad of woman selling Camel cigarettes - slashing of paint onto canvas - jagged lines create overpowering image - smile cut out of female smile from magazine ad - blank stare; frozen grin - ambiguous environment: vagueness, insecurity - combination of stereotypes; ironic comment on banal and artificial world of film and ads - one of series of six on woman theme - influenced by everything: Paleolithic goddesses to pin-up girls - think and think black lines dominate	
** Woman, I	
Helen Frankenthaler. 1963 CE. Acrylic on canvas. - painted directly on unprimed canvas; absorbs paint more directly - uses runny paint, sometimes thinned w/ turpentine - landscape as starting point; basis for imagery in the works - accentuates 2dness of canvas - worked in avant-garde New York School at mid-century	The Bay	
** Andy Warhol. 
1962 CE. 
Oil, acrylic, and silkscreen enamel on canvas. 
- screen=printing photographic images onto backgrounds of rectangular shapes - repeated imagery drains image of Monroe of meaning - 50 images from film still from a movie, Niagara - cult of celebrity - left, in color, represents her in life; right, in black and white, represents her death; work down four months after tragic death - Marilyn's public face appears highlighted by bold, artificial colors - private persona of individual submerged beneath public face - social characteristics magnified: brilliance of blonde hair, heavily applied lipstick, seductive expression	Marilyn Diptych	
** Claes Oldenburg. 1969-1974 CE. 
Cor-Ten steel, steel, aluminum, and cast resin; 
painted with polyurethane enamel. - first installed on Beinecke Plaza, New Haven, in 1969 - intended as a platform for public speakers; rallying point for anti-Vietnam era protests - erected secretly - tank-shaped platform base w/ lipstick ascending--anti-war symbolism - male and female forms unite: themes of death, power, desire, and sensuality - sculpture made of inexpensive and perishable materials - refurbished w/ steel, aluminum, fiberglass; reinstalled in 1974 in front of Morse College at Yale - first monumental sculpture by Oldenburg	Lipstick (Ascending) on Caterpillar Tracks	
** "Yayoi Kusama. 
Original installation and performance in 1966 CE. Mirror balls. - Kusama: internationally renowned Japanese-born artist; got start sowing large works of art featuring huge polka dots; one of foremost innovators of Happenings; works in a wide variety of media, including installations - originally featured as non-participant in 1966 Venice Biennale - 1500 large, mirrored, stainless steel balls placed on lawn under sign: ""Your Narcissism for Sale"" - artist offered balls for 1200 lira ($2 each) as commentary on commercialism and vanity of current art world - references ancient myth of Narcissus, young man so enraptured by own image in reflecting water, he stares at it indefinitely until he becomes a flower - later moved to water, where floating balls reflect natural environment (and viewers) around work; placement makes stronger connection to myth - move w/ currents of water and wind, reflecting organically made ever-changing viewpoints - installation has been exhibited in many places around the world, both in water and in dry spaces"	Narcissus Garden	
Great Salt Lake, Utah, U.S. Robert Smithson. 1970 CE. Earthwork: mud, precipitated salt crystals, rocks, and water coil. - coil of rock in part of Great Salt Lake; in extremely remote and inaccessible area that features abandoned mines and equipment - upon walking on, twisting and curling path changes participant's view from every angle - tractor w/ native stone used to create - a jetty is supposed to be a pier in the water; now transformed into curl of rocks sitting silently in vast empty wilderness - coil image seen in North American earthworks - artist liked blood red color of water due to presence of bacteria that live in high salt content
	Spiral Jetty	
"Delaware, U.S. Robert Venturi, John Rauch, and Denise Scott Brown (architects). 1978-1983 CE. Wood frame and stucco. - house designed for family of three - wife: musician; hence music room w/ two pianos, an organ, and a harpsichord - husband: bird watcher; large windows facing woods - post-modern mix of historical styles - Venturi's comment on International Style: ""Less is a bore"""	House in New Castle County	
Gustave Courbet. 1849 CE (destroyed in 1945). Oil on canvas. - submitted to the Salon of 1850-1851 - breaking stones down to rubble to be used for paving - poverty emphasized - figures born poor and will remain poor their whole lives - reaction to labor unrest of 1848: demanding better working conditions - large size of painting usually reserved for grand historical paintings, elevating commonplace into realm of legend and history - men turned away: lack of individuality
** The Stone Breakers	
"Honoré Daumier. 1862 CE. Lithograph. - Nadar was famous of taking aerial photos of Paris beginning in 1858 - presents Nadar as a quacky photography; in his excitement to get a daring shot he almost falls out of his balloon and loses his hat - every building has the word ""photographie"" on it - mocks claims that photography can be ""high art""; irony implied in title - done after court decision in 1862 that determined that photographs could be considered works of art - originally appeared in a journal: Le Boulevard - intrusive photography: Nadar's balloon reused in the 1870 Siege of Paris - foreshadows modern surveillance photographs"
** Nadar Raising Photography to the Height of Art	
Édouard Manet. 1863 CE. Oil on canvas. - created a sandal at the Salon of 1865 - traditional subject of reclining nude; inspired by Titian's Venus of Urbino - figure cold and uninviting, no mystery/joy - maid delivers flowers from an admirer - common name for prostitutes of the time - frank, direct, uncaring, and unnerving look startled viewers - simplified modeling; active brushwork - stark contrast of colors - a mistress was common to upper class Parisian men
** Olympia	
Jose María Velasco. 1882 CE. Oil on canvas. - primarily an academic landscape painter - specialized in broad panoramas of the Valley of Mexico - keen observer of nature: rocks foliage, clouds, waterfalls - rejected realist landscapes of Courbet; romantic landscapes of Turner - settled in Villa Guadalupe w. overview of the Valley of Mexico - dramatic perspective; small human figures - glories Mexican countryside	
** The Valley of Mexico from the Hillside of Santa Isabel (El Valle de México desde el Cerro de Santa Isabel)	

"Eadweard Muybridge. 1878 CE. Albumen print. - photography now advanced enough that it can capture moments the human eye cannot - cameras snap photos at evenly spaced points along a track, giving the effect of things happening in sequence - bridge the gap between still photography and movies - used a zoopraxiscope - great influence on painters - showed ""rocking horse"" position in art was unrealistic"	
** The Horse in Motion	
Claude Monet. 
1877 CE. 
Oil on canvas. 
- exhibited at the Impressionist exhibition of 1877 - one of a series depicting this train station - Monet famous for painting series of paintings on same subject at different times of day and different days of the year - originally meant to be hung together for effect: Haystacks were his first group to be hung this way - effects of steam, light, and color; not really about the machines or travelers - subtle gradation of light on the surface - forms dissolve and dematerialize; color overwhelms the forms	
** The Saint-Lazare Station	
Mary Cassatt. 
1890-1891 CE. 
Drypoint and aquatint. 
- Cassatt's world filled w/ women and children because not socially accepted for women to be alone with men - no posing or acting; figures possess a natural charm - decorative charm influenced by Japanese art - Japanese hair style; Japanese point of view: figure seen from the back - tenderness foreign to other Impressionists - part of a series of ten prints exhibited together - contrasting sensuous curves of female figure w/ straight lines of furniture and wall - pastel color scheme	

The Coiffure	
Vincent van Gogh. 1889 CE. Oil on canvas. - thick short brushstrokes - mountains in distance that Van Gogh could see at his hospital room in St.-Remy, steepness exaggerated - composite landscape: Dutch church, crescent moon, Mediterranean cypress tree - at one w/ forces of nature - parts of canvas can be seen through the brushwork; artist need not fill every space - strong left-to-right wavelike impulse in work, broken only by tree and church steeple - trees like green flames reaching into sky exploding w/ stars over a placide village; cypress tree a traditional symbol of death and eternal life - houses w/ touches of yellow to symbolize signs of life - church spire bridges sky and people

The Starry Night	

 1897-1898 CE. 
Oil on canvas. 
- painted during second stay in Tahiti between 1895-1901 - suffered from poor health and poverty; obsessed by thoughts of death - learned of death of daughter, Aline, in April 1897; deeply shaken; determined to commit suicide and have this painting be his artistic will and testament - story of life, right to left - right: birth, infant and three adults - center: mid-life; picking the fruit of the world - left: death (a figure derived from Peruvian mummy exhibited in Paris); Blue Idol represents ""The Beyond"" - figures in foreground represent Tahiti and an Eden-like paradise; background figures are anguished darkened figures - rejection of Greco-Roman influence; Egyptian figures used for inspiration; Japanese prints in solid fields of color and unusual angles; Tahitian imagery in Polynesian idol - Gauguin thought of painting as summation of artistic and personal expression"

Where Do We Come From? What Are We? Where Are We Going?	
Paul Cézanne. 1902-1904 CE. Oil on canvas. - one of eleven canvases of this view, series dominates Cezanne's mature period - had contempt for flat painting, wanted rounded and firm objects but ones that were geometric constructions made from splashes of undiluted color - used perspective through juxtaposing forward warm colors w/ receding cool colors - landscape rarely contains humans 0 not in countryside of Impressionism, more interested in geometric forms than dappled effects of light - not a momentary glimpse of atmosphere as in the Impressionists, but a solid and firmly constructed mountain and foreground - landscape seen from an elevation - invited to look at space, but not enter	Mont Sainte-Victoire	

Edvard Munch. 1893 CE. Tempera and pastels on cardboard. - figure walking along a wharf, boats are at sea in the distance - long thick brushstrokes swirl around composition - figure cries out in horrifying scream, the landscape echoes his emotions - said to have been inspired by an exhibit of a Peruvian mummy in Paris - discordant colors symbolize anguish - emaciated twisting stick figure w/ skull-like head - prefigures Expressionist art - painted of a series called The Frieze of Life - Art Nouveau swirling patterns

** The Scream	
*** A: Gustav Klimt
**** D: 1893
***** M:Oil and gold leaf on canvas 
Little of human form is actually seen: two heads, four hands, two feet - bodies suggested under a sea of richly designed patterning - male figure has large rectangular boxes; female figure has circular forms - suggests all-consuming love; passion; eroticism - spaced in indeterminate location against flattened background - gold leaf reminiscent of Byzantine mosaics	The Kiss	
"Chicago, Illinois, U.S. Louis Sullivan (architect). 1899-1903 CE. Iron, steel, glass, and terra cotta. - horizontal emphasis symbolizes continuous flow of floor space - maximum window areas to admit light, also to display store wares - non supportive role of exterior - cast iron decorative elements transformed store into beautiful place to buy beautiful things - influence of Art Nouveau in decorative touches - Sullivan motto: ""form follows function"" - exterior coated in decorative terracotta tiles; original interior ornament elaborately arranged around lobby areas, hallways, elevator - some historical touches in the round entrance arches and heavy cornice at top of building"	Carson, Pirie, 
** Scott and Company Building	
Auguste Rodin.
1884-1895 CE. 
Bronze 
six burghers offer their lives to the English king in return for saving their besieged city during the Hundred Years' War; English king insister burghers wear sackcloths and carry the key to the city - parallels between Paris besieged during the Franco=Prussian War of 1870 and Calais besieged by the English in 1347 - figures sculpted individually, then arranged as the artist thought best - figures suffer from privation; weak and emaciated - each w/ different emotion - central figure: Eustache de Saint-Pierre, who has large swollen hands an noose around neck, ready for execution - details reduced to emphasize overall impression - meant to be placed at ground level so people could see it close up; viewer forced to confront humanized individuals - rejected by town council of Calais as being inglorious; they wanted single allegorical figure - BIG BECAUSE NOT HAILED AS HEROES, BUT JUST PATHETIC HUMANS	The Burghers of Calais	

** Monticello	

"Virginia, U.S. Thomas Jefferson (architect). 1768-1809 CE. Brick, glass, stone, and wood. - ""little mountain"" (Italian) - chief building on Jefferson's plantation - symmetrical interior design - brick building, stucco applied to trim to give effect of marble - tall French doors and windows allow circulation in hot Virginia summers - appears to be one-story building w/ a dome, but balustrade hides second floor - inspired by Palladian villas in Italy and Roman ruins in France - octogonal dome - Jefferson obsessed with saving space in his home: very narrow spiral staircases, beds in alcoves or in walls between rooms"	

** The Oath of the Horatii	
*** A: Jacques-Louis David. 
**** D: 1784 CE
***** M: Oil on canvas. 
- exemplum virtutis - story of three Roman brothers (the Horatii) who do battle with three other brothers (the Curiatii--not painted) from nearby city; pledge their fidelity to their father and to Rome - one of three women on right Horatii engaged to one of Curiatii brothers; another is sister of Curiatii brothers - forms vigorous, powerful, animated, emphatic - gestures sweeping and unified - figures pushed to foreground - neoclassical drapery and tripartite composition - Caravaggio-like lighting and un-Roman architectural capitals (not Neoclassical in these aspects) - painted under royal patronage - created sensation at the Salon of 1785 - stiffness of men contrast with women's curved bodies


*** A: Jean-Antoine Houdon.
**** D 1788-1792 CE. 
***** M: Marble 
- dressed as 18th century gentleman - military associations minimized: epaulettes on should and sword cast to the side - naturalistic details: missing button on jacket; tightly buttoned vest around protruding stomach - seen as man of vision and enlightenment - badge of Cincinnatus on this belt: gentleman-farmer who left Mount Vernon to take up in American cause the way Cincinnatus from Roman Republic left farm to command Roman armies, then returned to farm - plow behind symbolizes his plantation - leans on Roman fasces: thirteen rods symbolize thirteen colonies, from which he gets his support

** George Washington	

London, England. Charles Barry and Augustus W. N. Pugin (architects).
 1840-1870 CE.
 Limestone masonry and glass. 
- competition held in 1835 for new Houses of Parliament after old one burned down: 97 entrants in contest; 91 in Perpendicular Gothic, 6 in Elizabethan style; thought to be native English styles - enormous structure of 1100 rooms, 100 staircases, 2 miles of corridors - modern office building cloaked in medieval clothes - Barry a classical architect, accounts for regularity of plan - Pugin a Gothic architect, added Gothic architectural touches to structure - profusion of Gothic ornament great than would appear in an original Gothic building - Big Ben is a clock tower, in a sense a village clock for all of England	Palace of Westminster (the Houses of Parliament)	
- situated between House of Commons and House of Lords - meant to be a space where constituents can meet their member of the Parliament - metal grills on doorways originally in House of Commons and marked off the spots where women could be seated to watch; now symbols of suffrage movement - central octagonal space w/ statues of Kings and Queens of England and Scotland - four lage mosaics over each doorway represents four saints who represent different areas of UK: England = St. George, Scotland = St. Andrew, Wales = St. David, Northern Island = St. Patrick	


** Central Lobby (from Palace of Westminster)	

- Gothic - when old Houses of Parliament burned to the ground, this remained as last vestige of medieval parliament building - started under William II as largest hall in England at the time - meant for grand ceremonial occasions: coronations, feats; later used as law court  - bare walls probably decorated w/ tapestries - windows placed high up surrounded by Romanesque arches - original roof replaced; debate over how originally vaulted; w/ beams that came down to floor denoting main aisle and two side aisles? - remodeled roof under Richard II - hammerbeam style; made of oak - Richard II also placed six statues of kings at one entrance, alongside his emblems - when old Houses of Parliament burned, remained as last vestige of medieval parliament building	

Westminster Hall (from Palace of Westminster)	
A: "Francisco de Goya.
D: 1810-1823 CE (published 1863).

 Etching, drypoint, burin, and burnishing. - Disaster of War: 80 etchings and aquatints; published 35 years after Goya's death; critical of French occupation of Spain and the subsequent Spanish rulers; influenced by Spain's continuous warfare; original title: ""Fatal Consequences of Spain's Bloody War with Bonaparte and Other Emphatic Caprices""; explores themes of war, famine, and politics - And There's Nothing to be Done: bitterly ironic and sardonic; guns at very close range point toward victims, assumedly Spanish patriots, who will summarily killed by French soldiers; mangled body on the ground; are they civilians or soldiers who are being shot?"	Y no hai remedio (And There's Nothing to Be Done), from Los Desastres de la Guerra (The Disasters of War), plate 15	
"Jean-Auguste-Dominique Ingres. 1814 CE. Oil on canvas. - Raphael-like face - Turkish elements: incense burner, peacock fan, tapestry-like turban, hashish pipe, hence the name ""odalisque"" - inconsistent arrangement of limbs: rubbery arm, elongated back, placement of leg, one arm longer than the other - heavily influenced by Italian Mannerism in exaggerated body forms - further development of female nude form"	

La Grande Odalisque	
A: "Eugène Delacroix.
D: 1830 CE. 
M: Oil on canvas. 
- July Revolution of 1830; Liberty w/ French tricolor marches over barricades to overthrow government soldiers - red/white/blue echo throughout  - strong pyramidal structure - child w/ pistols symbolizes role of students in revolt; middle class by man in top hat carrying rifle; lower class by man at extreme left w/ sword in hand and pistol in belt - Liberty wears a red Phrygian cap, worn in ancient world by freed slaves - Notre Dame Cathedral seen through smoke on far rights; French tricolor raised on its tower - Parisian landmark of Notre Dame mixed w/ true historical event and allegorical and symbolic figures - memorializes overthrow of French government in favor of the ""Citizen King"" Louis-Philippe - acquired by French state in 1831, but not exhibited publicly for 25 years because of its subversive message"	

** Liberty Leading the People	
*** Joseph Mallord William Turner.	
D: 1840 CE. 
M: Oil on canvas. 
- exhibited at Royal Academy in 1840, w. excerpt from Turner's own poem called ""The Fallacies of Hope""  - based on true story of even in 1781 where slave ship (The Zong) sailed for Americas full of slaves; insured against accidental drowning but not against sickness, policy instituted to force captains to treat slaves humanely; knowing he would not collect insurance money on sick and dying slaves, throws them overboard - inspired by account fo scandal published in a book by Thomas Clarkson, which had been reprinted in 1839 - England freed slaves in 1833 by act of Parliament; some exceptions not addressed until 1843 - emotional use of color - rapid brushwork - recognizable forms (ship, hands, chains) reduced in size and pale in comparison to mightiness of turbulent seascape - bloody sunset acts as symbol of scene taking place - use of sublime enhances dramatic impact"


** Slave Ship (Slavers Throwing Overboard the Dead and Dying, Typhoon Coming On)	
*** Artist: Thomas Cole 
**** Date: 1836 CE.
***** Material: Oil on canvas. 	
Description: - actual view in Massachusetts - division of landscape into two clearly contrasting areas: Roman on left and Classical on right - self-portrait in foreground amid dense forest (impenetrably thick, w/ broken trees) and a wild landscape w/ storms; the sublime - right: man's touch seen in light, cultivated fields, boats drifting down river - painted as reply to British book that alleged Americans had destroyed a wilderness w/ industry - painted for exhibit and the National Academy of Design, accounts for unusually large size

** The Oxbow (View from Mount Holyoke, Northampton, Massachusetts, after a Thunderstorm) :1800s:
Artist:Louis-Jacques-Mandé Daguerre. 
Date: 1837 CE. 
Daguerreotype. - inspired by painted still lifes, like vanitas paintings - variety of textures: fabric, wicker, plaster, framed print, metal, wood, etc - new art form inspired by older	Still Life in Studio	


** The Death of Marat                                                 :1700s:
*** A: Jacques-Louis David 
**** D: 1793

** The Swing                                                          :1700s:
A:Jean-Honoré Fragonard. 
D: 1767 CE. 
M: Oil on canvas. - figures small in dominant garden-like setting - atmospheric perspective - puffy clouds; reich vegetation; abundant flowers; sinuous curves - patron in lower left (lover of lady) looking up skirt of young lady who swings flirtatiously, boldly kicking off her shoe at a Cupid sculpture - unsuspecting bishop swings her from behind (represents marriage/her husband) - Cupid asks young lady to be discreet and/or may be a symbol for secret hiding of patron - Cupids bashful at flaunted affair

** 
Elisabeth Louise Vigée Le Brun. 1790 CE. Oil on canvas. - forty self-portraits exist, all highly idealized - looks at viewers as she paints portrait of Marie Antoinette, whois rendered from emory since she was killed during French Revolution; subject in painting looks admiringly upon painter - light Rococo touch to coloring - inspired by portraits of Rubens	Self-Portrait	
Joseph Wright of Derby. c. 1763-1765 CE. Oil on canvas. - influenced by meeting of provincial group of intellectuals called the Lunar Society, who met once a month to discuss current scientific discoveries and developments - orrey: early form of a planetarium, imitating the motion of the solar system - lamp in center (out of view) = sun - mixed group of middle class people in attendance representing all ages of me; young woman seated to left - some curious, some contemplate, some in wonder, som fascinated - philosopher stops to clarify a point to the note-taker on the left - each face aspect of phases of the moon - one of series of candlelight pictures by Wright; inspired by Caravaggio's use of tenebrism

A Philosopher Giving a Lecture on the Orrery	

Miguel Cabrera. c. 1750 CE. Oil on canvas. - child prodigy (1651-1695) - creole woman, became a nun in 1669 - feminist culture survived in Mexican convents where privileged nuns lived in comfort w/ servants and households - literary figure, published books widely read; wrote poetry and theatrical pieces - maintained a great library - instrumental in giving girls and education in a male-dominated world - wearing habit of religious order of the Hermits of St. Jerome nuns of Mexico City; including the escudo (framed vellum painting) - seated in library surrounded by symbols of faith and learning - many portraits survive, but all images derive from now lost self-portrait - painting done 55 years after death for admirers	

** Portrait of Sor Juana Ines de la Cruz	

Northern highlands, Peru. Chavín. 900-200 BCE. Stone (architectural complex); granite (Lanzón and sculpture); hammered gold alloy (jewelry). - religious capital - 60 meters tall w/ jaguar sculpture (symbol of power) - hidden entrance to temple led to stone corridors - coordinated w/ adjacent river --> reference to water sources and their importance to society?	Chavín de Huántar	
"- inside Old Temple, maze-like system of hallways - at center, underground, is Lanzon (Spanish for ""blade"") stone - fifteen feet tall; blade shaped - depicts powerful figure part human (body) and part animal (fangs, claws) - head of snakes and face of jaguar - eyebrows terminate in snakes - flat relief; designs in curvilinear pattern - served as cult figure - center of pilgrimage; however, few had access to Lanzon Stone - modern scholars hypothesize that stone acted as oracle"	Plan and Lanzón Stone (part of Chavín de Huántar)	
- located on ruins of stairway - shows jaguars in shallow relief	Relief sculpture (part of Chavín de Huántar)	
- worn by both sexes under the nose - held in place by semi-circular section at top - two snake heads on either end - makes wearer into supernatural being during ceremonies	Nose ornament (Chavín de Huántar)	
Chiapas, Mexico. Maya. 725 CE. Limestone (architectural complex). - city set on high terrace; plaza surrounded by important buildings - flourished c. 300-800 CE	Yaxchilán	
- built by ruler Bird Jaguar IV, or his son who dedicated it to him - overlooks main plaza - three doors leading to central room decorated w/ stucco - roof remains nearly intact, w/ large roof comb - corbel arch interior	

** Structure 40, Yaxchilán	
- lintel originally set above central doorway of Structure 23 - building dedicated to Lady Xoc - Lady Xoc (bottom right) invoking Vision Serpent to commemorate husband's rise to throne - holds bowl w/ bloodletting ceremonial items: stinging spin and bloodstained paper - Vision Serpent has two heads: on w/ warrior emerging from mouth, other w/ Tlaloc - inscription written as mirror image: extremely unusual in Mayan script; uncertain meaning, maybe indicates she had vision from other side of existence, and she is acting as intercessor/shaman	Lintel 25, Structure 23, Yaxchilán	
- restored temple structure - remains of roof comb w/ perforations - three central doorways lead to large single room - corbel arch interior	

** Structure 33, Yaxchilán	
Montezuma County, Colorado. Ancestral Puebloan (Anasazi). 450-1300 CE. Sandstone. - pueblo built into sides of cliff, housed about 250 people - clans moved together for mutual support and defence - top-ledge stores all supplies, cool and dry area out of way, accessible only by ladder - plaza in front of abode structure; kivas face plaza - each family received one room in dwelling - farming done on plateau above pueblo, everything had to be imported into structure, including water	Mesa Verde cliff dwellings	
Adams County, southern Ohio. Mississippian (Eastern Woodlands). c. 1070 CE. Earthwork/effigy mound. - many mounds enlarged and changed over years, not built in one campaign - effigy mounds popular in Mississippian culture - influenced by comets? astrological phenomenon? head pointed to summer solstice sunset? - rattlesnake as symbol in Mississippian iconography; could this play a role in interpreting this mound? - snakes associated w/ crop fertility - no burials/tempes associated w/ this mound - theory: representation of Halley's Comet in 1066	

** Great Serpent Mound	
Tenochtitlan (modern Mexico City, Mexico). Mexica (Aztec). 1375-1520 CE. Stone (temple); volcanic stone (The Coyolxauhqui Stone); jadeite (Olmec-style mask); basalt (Calendar Stone). - Tenochtitlan laid out on grid; city seen as center of world - two temples atop pyramid, each w/ separate staircase - north: dedicated to Tlaloc - south: dedicated to Huitzilopochtli - spring and autumn equinoxes: sun rises between the two - large braziers put on top where sacred fires burned - temples begun in 1375; rebuilt six times, destroyed by Spanish in 1520	Templo Mayor (Main Temple)	
"- ""she of the golden bells"", because of the bells she wars as earrings - Aztecs similarly dismembered enemies and threw them down stares of great pyramid to land on disk of Coyolxauhqui, like Coyolxauhqui's fate - circular relief sculpture - Coyolxauhqui and her many brothers plotted death of mother, Coatlicue, who became pregnant after tucking a ball of feathers down her bosom; when Coyolxauhqui chopped of Coatlicue's head, child popped out of severed head fully grown, and dismembered Coyolxauhqui, who fell dead at base of shrine - represents dismembered moon goddess placed at base of twin pyramids of Tenochtitlan - once brilliantly painted"	

** Coyolxauhqui Stone (part of Templo Mayor )	
- circular shape reflects cyclic nature of time - place where rituals took place on certain days - Aztecs felt they needed to feed Sun god human hearts and blood regularly - tongue in center coming from god's mouth and sacrificial flint knife used to slash open victims - altar to murder victims, then threw them down steps of temple to base where Coyolxauhqui Stone rests	Calendar Stone (part of Templo Mayor)	
- found on site, actually much older work executed by Olmecs - Olmec works have characteristics frown on face; pugnacious visage; heavy lidded eyes; headgear suggested - shows Aztecs collected and embraced artwork from other cultures	Olmec-style mask (part of Templo Mayor)	
Mexica (Aztec). 1428-1520 CE. Feathers (quetzal and cotinga) and gold. - 400 long green feathers are tails of sacred quetzal birds; male birds produce only two such feathers each - 400 symbolizes eternity - headdress probably part of collection of artifacts given by Motecuhzoma (Montezuma) to Cortez for Charles V of the Holy Roman Empire

Ruler's feather headdress (probably of Motecuhzoma II)	

Inka. c. 1440-1533 CE. Sheet metal/repoussé, metal alloys. - maize principal food source in Andes; celebrated by having sculptures fashioned out of sheet metal - black maize common in Peru; oxidized silver reflects that - may have been part of garden in which full-sized metal sculptures of maize plants, and other items, were put in place alongside plants - may have been used to ensure successful harvest	Maize cobs	
Central highlands, Peru. Inka. c. 1440 CE; convent added 1550-1650 CE. Andesite. - historic capital of Inkan empire - in shape of puma, a royal animal - modern plaza is in the place where puma's belly would be - head of a fortress; heart a central square	City of Cusco, plan	
- remains of Inkan Temple of the Sun form base of Santo Domingo convent built on top - original exterior walls of Temple decorated in gold to symbolize sunshine - ashlar masonry - Qorikancha: golden enclosure, once was most important temple in Inkan world - once was observatory for priests to chart skies - interior courtyard said to have been entirely covered in gold - walls taper upward; examples of Inkan trapezoidal architecture	Qorikancha: main temple, church, and convent of Santo Domingo (part of City of Cusco)	
- complex outside of Cusco, Peru, at head of puma-shaped plan - ashlar masonry - ramparts contain stones weighing up to 70 tons, brought from quarry two miles away	

Walls at Saqsa Waman (part of City Cusco)	
Central highlands, Peru. Inka. c. 1450-1540 CE. Granite (architectural complex). - originally functioned as royal retreat - estate of 15th century Inkan rulers - so remote; probably not used for administrative purpose in Inka word - buildings built of stone w/ perfectly carved rock rendered in precise shapes and grooved together; thatched roofs - 200 buildings, mostly houses, some temples, palaces, baths, even astronomical observatory; mostly using basic trapezoidal shape - terrace farming	Machu Picchu	
- used to chart sun's movements - ashlar masonry	


Observatory (part of Machu Picchu)	
"- ""Hitching post of the Sun"", aligns w/ sun at spring and autumn equinoxes when sun stands directly over pillar, creating no shadow - Inkan ceremonies held in concert w/ this event"	Intihuatana Stone (part of Machu Picchu)	
Inka. 1450-1540 CE. Camelid fiber and cotton. - rectangular shape; slit in center for head, then tunic folded in half and sides sewn for arms - composition comprised t'oqapu; individual square may be symbolic of individuals/events/places - contains large number of t'oqapu - wearing such an elaborate garment would indicate status - may have been worn by Inkan ruler - exhibits Inkan preference for abstract designs, standardization of designs, and expression of unity and order	All-T'oqapu tunic	
Lenape (Delaware tribe, Eastern Woodlands). c. 1850 CE. Beadwork on leather. - held at hip level; strap across chest - constructed of trade cloth: cotton, woo, velvet, or leather - beadwork not done in Americans before European contact; beads imported from Europe - meant to be paired with men's ceremonial outfits - indicated prestige and status - first used completely for decoration; later had a pouch - inspired by Europeans' ammo bags	Bandolier bag	
Kwakwaka'wakw, Northwest coast of Canada. Late 19th century CE. Wood, paint, and string.  - worn by native people of Pacific Northwest, western Canada, Alaska - worn over head as part of complete body costume - during ritual performance, wearer opens and closes transformation mask using strings - bird exterior opens to reveal human face on interior (w/ birdlike features, ie sharp nose) - at moment of transformation, performer turns back to audience to conceal action and heighten mystery	Transformation Mask	
Attributed to Cotsiogo (Cadzi Cody), Eastern Shoshone, Wind River Reservation, Wyoming. c. 1890-1900 CE. Painted elk hide. - worn as robes over shoulders of warrior; deeds celebrated on hide - conveyed biographical details; personal accomplishments; heroism; battles - men painted hides to narrate event - eventually painted hides for European and American markets - depicted traditional aspects of Plans people culture that were nostalgia rather than practical: bison hunt w/ bow and arrow --> nomadic hunting gone, bison nearly extinct - bison considered to be gifts from Creator - horses in common use around 1750, liberated Plains people - Sun Dance conducted around bison head: outlawed by US government; viewed as threat to order - Sun Dance: men dance; others sing, prepare feast, drum , construct lodge - teepee - exterior poles reach spirit world or sky - fire represents heart - doorway faces east to meet new day	Painted Elk Hide	
Maria Martínez and Julian Martínez, Tewa, Puebloan, San Ildefonso Pueblo, New Mexico. c. mid-20th century CE. Blackware ceramic. - highly polished surfaces - contrasts of shiny black and matte black finishes - comes from 1000 year old tradition of pottery making in Southwest - at time of production, pueblos in decline; modern life replacing traditional - work sparked revival in pueblo techniques - Maria made pots; developed and invented more shapes than traditional pueblos used - Julian painted pots; uses revival of ancient mythic figures and designs - exceptional symmetry; walls of even thickness; surfaces free of imperfections	Black-on-black ceramic vessel	
"Shona peoples (Southeastern Zimbabwe). c. 1000- 1400 CE. Coursed granite blocks. - Zimbabwe defrived from Shona term meaning ""venerated houses"" or ""houses of stone"" - prosperous trading center and royal complex - stone enclosure, probably a royal residence - walls: 800 feet long, 32 feet tall, 17 feet thick at base - conical tower modeled on traditional shapes of grain silos; control over food symbolized wealth, power, and royal largesse - walls slope inward toward top, made of exfoliated granite blocks - internal and external passageways tightly bounded, narrow, and long, forcing occupants to walk in single file, paralleling experiences in African bush - tower resembles granary; represented good harvest and prosperity"	Conical tower and circular wall of Great Zimbabwe	
Mali. Founded c. 1200 ce; rebuilt 1906-1907 CE. Adobe. - three tall towers, on in center is mihrab - crowning ornaments have ostrich eggs: symbols of fertility and purty - torons for permanent ladders for maintenance of building - vertical fluting drains water off surfaces quickly - largest mud-brick mosque in world	Great Mosque of Djenné	
"Edo peoples, Kingdom of Benin (Nigeria). 16th century CE. Cast brass. - 900 brass plaques produced; between 16 and 18 inches - decorated walls of royal palace in Benin - part of sprawling palace complex; wooden pillars covered w/ brass plaques - shows aspects of court life in Benin culture - Oba (""king"") believed to be direct descendant of Oranmiyan, legendary founder of the dynasty - only the Oba allowed to be shielded in way depicted on plaque - hierarchical proportions - symbols of high rank emphasized - stepping on fallen leader - emphasis on heads; bodies often small and immature - lost wax process - ceremonial scene at court - high relief"	Wall plaque from Oba's palace	
Ashanti peoples (south central Ghana). c. 1700 CE. Gold over wood and castgold attachments. - symbol of Ashanti nation; held in Ghana - contains soul of nation - never used as a stool; not allowed to touch ground - new king raised over stool - carried to king on a pillow; he alone is allowed to touch it - taken out on special occasions - entire surface inland w/ gold - bells hang from side to warn king of danger - replicas often used in ceremonies, but each is different - War of the Golden Stool: March-September 1900; conflict over British sovereignty in Ghana (formerly Gold Coast); British representative tried to sit; caused uproar and subsequent rebellion; ended in British annexation and Ashanti de facto independence	Golden Stool (Skia dwa kofi)	
"Kuba peoples (Democratic Republic of the Congo). c. 1760-1780 CE. Wood. - commemorative portraits of Kuba rulers, represented in ideal state - representation of deceased king's spirit; made after death - each king commemorated by symbols on base of figure; this king has sword in left hand in non-aggressive pose, handle facing out - one of earliest existing African sculptures; oldest ndop in existence - rubbed w/ oil to protect from insects - surrogate for king in absence - kept in king's shrine w/ other works called a set of ""royal charms"" - royal regalia: bracelets, arm bands, belts, headdress - characteristics: cross-legged pose, sits on base; face seems uninvolved and above mortal affairs; peace knife in left hand"	Ndop (portrait figure)	
- photo of Kuba ruler enthroned wearing royal regalia: headdress, necklace of leopard teeth, sword, lance, drums of reign, basket - made in 1971 capturing royal event - continuous tradition of honoring a Kuba king - costuming extremely elaborate; could weight 185 pounds, needed help to move; represents splendor of court, greatness, and responsibilities - symbolizes ruler's wealth, status, power - Kuba taste of accumulation of objects - often buried w/ material after death	Kuba Nyim (ruler) Kot a Mbweeky II in state dress with royal drum in Mushenge, Congo (context image for Ndop)	
Kongo peoples (Democratic Republic of the Congo). c. late 19th century CE. Wood and metal. - spirits embedded in images; can be called upon to bless or harm others, cause death, or give life - to prod image into action, nails and blades often inserted into work or removed from it - medical properties inserted into body cavity, thought to be a person's life/soul - nails pounded into figure - alert pose	Power figure (Nkisi n'kondi)	
Baule peoples (Côte d'Ivoire). Early 20th century CE. Wood and pigment. - presented at Mblo performances where individual honored by having ritual dances and tributes are performed in someone's honor - honoree receives mask as gift that reflects artistic double - commissioned by group of admirers, not by individual - dancer who wears mask and wears clothes of honored person accompanied by actual person during performance - idealized representation of real person; not portrait in modern sense of the term - portraits of real people, even if commemorative, are rare in African art - broad foreheads, pronounced eye socks, column-shaped nose - quiet faces; introspective looks; peaceful face; deditative; eyebrows in an arch	Portrait mask (Mblo)	
Chokwe peoples (Democratic Republic of the Congo). Late 19th to early 20th century CE. Wood, fiber, pigment, and metal. - female masks used by men in ritual dances; men covered w/ identities masked; dressed as women w/ braided hair - ritual where men move like women - Chokwe a matriarchal society - depicts female ancestors - discarded when not in use; can be buried w/ dancer - characteristics: enlarged eye sockets; pushed-in chin; slender nose; high forehead; balanced features; almost-closed eyes	Female (Pwo) mask	
Sande Society, Mende peoples (West African forests of Sierra Leone and Liberia). 19th to 20th century CE. Wood, cloth, and fiber. - only African wooden masks worn by women - idealized female beauty - elaborate hairstyle symbolizes wealth; worn by men of status - large forehead - small eyes in shape of slits - tight-lipped mouth symbolizing secrets not revealed - Sande society: group of women who prepare girls for adulthood and their role in society - costumed women war black gown made of raffia that hides the body - costumed as a Sowei, water spirit; rings around neck symbolize concentric waves from which Sowi breaks through surface - mask rests on head; head not placed inside - coated w/ palm oil for lustrous effect - black color symbolizes water, coolness, humanity - individuality of each is stressed	Bundu mask	
"Igbo peoples (Nigeria). c. 19th to 20th century ce. Wood. - ""strong right arm"" thus physical prowess - honors right hand, which holds tools or weapons, makes sacrifices, conducts rituals, and alerts to speak at public forums - traditional masculine associations of strength and potency - carved from hardwoods considered masculine - tells of owner's morality, prosperity, achievements, genealogy, social rank - personal god of achievement and success - requires blessings before use; consecrated w/ offerings before kinsmen - enormous horns symbolize power - as man achieves more success he might commission more elaborate version - maintained in the man's home; destroyed when owner dies; another man can reuse it if not destroyed"	Ikenga (shrine figure)	
"Mbudye Society, Luba peoples (Democratic Republic of the Congo). c. 19th to 20th century CE. Wood, beads, and metal. - helps user remember key elements in a store: court ceremonies, migrations, heroes, kinship, genealogy, lists of kings - carved from wood in hourglass shape, then adorned w/ shells, beads, or metal - reader holds in left hand and traces designs w/ right index finger - back resembles tortoise - reading example: one colored bead can stand for an individual; large beads surrounded y smaller beads ins king and court; lines of beads journeys/paths - each board's design unique and represents divine revelations of a spirit medium expressed in sculptural form - controlled by mbudye: council who interpret political/historical aspects of Luba society - zoomorphic elements symbolize crocodile; dual nature metaphor for Luba's political organization w/ two interdependent leaders: kakungulu (head of mbudye) and kaloba (""owner of the land""; chief)"	Memory Board (Lukasa)	
Bamileke (Cameroon, western grassfields region). c. 19th to 20th century CE. Wood, woven raffia, cloth, and beads. - only important people in society can own and wear aka; used at a royal court - elite Kuosi masking society owns and wears the masks; worn on important ceremonial occasions - beadwork symbol of power - symbolizes features of an elephant: long trunk, large ears ( symbolizes trunk and power) - fits over head and two folds hang down in front and behind body - human face - maskers dance barefoot to a drum and gong; wave spears and horsetails	Aka elephant mask	
Fang peoples (southern Cameroon). c. 19th to 20th century CE. Wood. - placed on top of cylinder-like containers made of bark that hold bones of important clan leaders - feet dangling over rim in gesture of protecting contents against gaze of women or young boys - composed of characteristics Fang people place high value on: tranquility, introspection, vitality - surfaces ritually rubbed w/ oils to add luster and protect against insects - prominent belly button and genitals emphasize life; prayerful gesture and somber look to emphasize death - abstraction of human body an attraction for early 20th century artists	Reliquary figure (bieri)	
Olowe of Ise (Yoruba peoples). c. 1910- 1914 ce. Wood and pigment. - Olowe of Ise carved posts for rulers of Ekiti-Yoruba kingdom in Nigeria - one of four carved for the palace at Ikere - negative spaces create openness - king focal point in relationship between his figures and others presented on this post - behind: large-scale warrior wife supporting throne; crowns king during coronation; protects him during his reign - small figures: junior wife; flute player is Esu, trickster god; a now-missing fan bearer - most posts painted; traces of paint remain	Veranda post of enthroned king and senior wife (Opo Ogoga)	
"Lhasa, Tibet. Yarlung Dynasty. Believed to have been brought to Tibet in 641 CE. Gilt metals with semiprecious stones, pearls, and paint; various offerings. - enshrined in Jokhang Temple; Tibet's earliest and foremost Buddhist temple - temple founded in 647 CE by first ruler of a unified Tibet - Jowo = ""lord""; khang = ""house"" - statue thought to have been blessed by Buddha himself; believed to have been crafted in India during his lifetime - depiction of Buddha Shakyamuni as young man, around age of 12 - disappeared in 1960s during Chinese Cultural Revolution - 1983: lower part found in rubbish heap; upper part in Beijing; restored in 2003"	Jowo Rinpoche from the Jokhang Temple	
Bamiyan, Afghanistan. Gandharan. c. 400-800 CE (destroyed in 2001). Cut rock with plaster and polychrome paint. - Bamiyan at western ed of silk route; trading and religious center - two huge standing Buddhas, one 175 feet tall, other 115 feet tall - first colossal Buddhas - niche shaped like a halo (mondria) around the body - smaller Buddha: Sakyamuni, the historical Buddha - larger Buddha: Vairocana, the universal Buddha - originally covered w/ pigment and gold - cave galleries wave through cliff face; some painted w/ wall paintings and images of seated Buddha - pilgrims can walk through cave galleries into passageways that lead to level of Buddha's shoulders - models for later large-scale rock-cut images in China - destroyed by Taliban in act of iconoclasm in March 2002	Buddha	
Arab, North Africa, or Near East. Abbasid. c. eighth to ninth century CE. Ink, color, and gold on parchment. - Arabic read right to left - kufic script: strong uprights and long horizontals - great clarity of text important bc several readers read book at once, some at a distance - consonants scripted, vowels indicated by dots or markings around - Korans compiled and codified in mid-7th century; earliest surviving Koran form 9th century	Folio from the Qur'an	
Muhammad ibn alZain. c. 1320-1340 CE. Brass inlaid with gold and silver. - signed by artist six times - original use: washing hands at official ceremonies - later use: baptisms for French royal family (association w/ St. Louis fictional) - hunting alternate w/ battle scenes along side - mamluk hunters and Mongol enemies - bottom and top of bowl: decorated w/ fish, eels, crabs, frogs, crocodiles	Basin (Baptistere de St. Louis)	
Maqsud of Kashan. 1539-1540 CE. Silk and wool. - huge carpet, one of a matching pair, from the funerary mosque of Shaykh Safial-Din; probably made when shrine was enlarged - prayer carpet - medallion in center perhaps represents inside of dome w/ sixteen pendants - mosque lamps hang from two of pendants; one lamp smaller than other; larger lamp placed further away so it would appear same size - corner squinches also have pendants completing feeling of looking into a dome - world's oldest dated carpet - woven by ten people, probably men; women did weaving this period, but importance of location and size of project indicates men entrusted w/ its execution - dark blue background covered by leaves and flowers on stems - cartouche w/ artist's name, date, and three lines of poetry	The Ardabil Carpet	
Islamic; Persian, Il'Khanid. c. 1330-1340 CE. Ink and opaque watercolor, gold, and silver on paper. - Iranian manuscript - large painted surface area; calligraphy diminished - areas of flat color - spatial recession indicated by overlapping planes - atmospheric perspective seen in light bluish background - ancient Iranian king from Sasanian dynasty - represents ideal kings; wers crown and golden halo - karg is a unicorn he fought during this trip to India - Illustration from the Book of Kings - wears garment of European fabric - Chinese landscape conventions seen in background	Bahram Gur Fights the Karg, folio from the Great Il-Khanid Shahnama	
Shahnama. Sultan Muhammad. c. 1522-1525 CE. Ink, opaque watercolor, and gold on paper. - Shahnama (Book of Kings): Persian epic poem by Firdawsi telling ancient history of Persia; 259 illustrated pages - first king, Gayumars, enthroned before community - left: son Siamak; right: grandson Hushang - court appears in semicircle below him; court attire: wearing leopard skins - harmony between man and landscape - minute details do not overwhelm harmony of scene - angel Surush tells Gayumars his son will be murdered by the Black Div, son of demon Ahriman - sense of lightness and airiness reference to paradise	The Court of Gayumars	
Mecca, Saudi Arabia. Islamic. Pre-Islamic monument; rededicated by Muhammad in 631-632 CE; multiple renovations. Granite masonry, covered with silk curtain and calligraphy in gold and silver wrapped thread. - said to have been built by Ibrahim and Ishmael for God - existing structure encases blackstone in eastern corner, only part of original structure by Ibrahim that survives - cube-like in shape; covered in textiles - destination for hajj; circumambulate counterclockwise seven times - rededicated by Muhammad to Allah	The Kaaba	
Jerusalem. Islamic, Umayyad. 691-692 CE, with multiple renovations. Stone masonry and wooden roof decorated with glazed ceramic tile, mosaics, and gilt aluminum and bronze dome. - domed wooden octagon - influenced by centrally planned buildings - columns taken from Roman monuments - sacred rock (Noble Enclosure; Foundation Stone) where Adam was buried (presumably), Abraham nearly sacrificed Isaac, Muhammad ascended heaven, Temple of Jerusalem was located - meant to rival Christian church of the Holy Sepulcher in Jerusalem, although it was inspired by its domed rotunda - Mosaic Arabic calligraphy urges Muslims to embrace Allah as one god; indicates Christian notion of Trinity is aspect of polytheism - oldest surviving Quran verses; first use of Quran verses in architecture - pilgrimage site for faithful - erected by Abd al-Malik, caliph of Umayyad Dynasty	Dome of the Rock	
Isfahan, Iran. Islamic, Persian: Seljuk, Il-Khanid, Timurid and Safavid Dynasties. c. 700 CE; additions and restorations in the 14th, 18th, and 20th centuries CE. Stone, brick, wood, plaster, and glazed ceramic tile. - large central rectangular courtyard surrounded by two-story arcade - each side of courtyard w/ centrally placed iwan; may be first mosque to have this feature - one iwan is entry for private spaced used by sultan and his retinue; dome adorned by tiles - qibla iwan largest and most decorative; size indicates direction to Mecca	Great Mosque (Masjid-e Jameh)	
"Nabataean Ptolemaic and Roman. c. 400 BCE-100 CE. Cut rock. - Petra was central city of Nabataeans (nomadic peoples) - built along caravan route - dead buried in tombs cut out of sandstone cliffs - 500 royal tombs in the rock, but no human remains found; burial practices unknown - ""red rose city"""	Treasury, Monastery and Great Temple of Petra, Jordan	
- lower story w/ influence of Greek and Roman temples - columns not proportionally spaced - upper floor: broken pediment w/ central tholos - combination of Roman and indigenous traditions - Nabataean concept and Roman features - Greek, Egyptian, Assyrian gods on facade	Treasury at Petra	
- in sacred precinct on southern citadel hill - dedicated to Dushara (principal deity; unique to Petra) -place of worship for a pantheon of deities	The Great Temple at Petra	
Madhya Pradesh, India. Buddhist; Maurya, late Sunga Dynasty. c. 300 BCE-100 CE. Stone masonry, sandstone on dome. - Buddhist shrine, mound shaped, faced w/ dressed stone - three umbrellas at top, representing Buddha, Buddha's Law, and Monastic Orders - railing at crest of mound surrounds umbrellas, symbolically a sacred tree - double stairway at sound end leads from base to drum, where there is a walkway for circumambulation - originally painted white - hemispherical dome replication of dome of heaven - four toranas grace entrances, at cardinal points - torana: richly carved scenes on architraves; Buddha does not appear himself, but symbolized by empty throne/ tree, under which he meditated; some may also represent sacred sites where Shakyamuni Buddha visited/taught; horror vacui of composition; high-relief - 600 donors have inscriptions carved into stupa, revealing project funded by women as well as men; common people as well as monks	Great Stupa at Sanchi	
Central Java, Indonesia. Sailendra Dynasty. c. 750-842 CE. Volcanic-stone masonry. - massive Buddhist monument contains 504 life-size Buddha's 1460 narrative relief sculptures on 1300 panels 8200 feet long; there are 1500 stupas and one million carved blocks of stone - iconographically complex and intricate; many levels of meaning; may reflect Buddhist cosmology - circumambulation on each terrace; six concentric square terraces topped by three circular tiers w/ great stupa at summit - pyramidal in form, aligned w/ the four cardinal points - lower stories represent world of desire and negative impulses; middle areas represent world of forms, people have to control these negative impulses; top story world of formulas, where physical world and worldly desire are expunged - pilgrimage - five terraces of identical stepped square plan - 72 openwork Buddhas, each w/ preaching mudra - on top enclosed stupa - rubble faced w/ carved volcanic stone	Borobudur Temple	
- densely packed scene: horror vacui - queen majestic and at rest before giving birth - brought up to city in great ceremonial procession - ready to give birth to her son	Queen Maya Riding a Horse Carriage Retreating to Lumbini to Give Birth to Prince Siddhartha Gautama (from Borobudur Temple)	
"Hindu; India (Tamil Nadu), Chola Dynasty. c. 11th century CE. Cast bronze. - vigorously dancing w/ one foot on a dwarf, Demon of Ignorance; often depicted in flaming nimbus - flying locks of hair terminate in rearing cobra heads - one hand sounds drum that he dances to, another has flame - four hads - epicene quality - periodically destroys universe so it can be reborn again - unfolds universe out of drum held in one of right hands; preserves it by uplifting other right hand in gesture indicating ""do not be afraid"" - shave has third vertical eye barely suggested between two other eyes; once burned god Kama w/ this eye"	Shiva as Lord of Dance (Nataraja)	
"Khajuraho, India. Hindu, Chandella Dynasty. c. 930-950 CE. Sandstone. - placed on high pedestal - series of shapes that build to become large tower; complicated intertwining of similar forms - center: ""embryo"" room w/ shrine, very small, only enough space for priest - corbelled roofs w/ beehive quality - grouped w/ series of other temples in Khajuraho - ashlar masonry - bands of horizontal boldings unite temple - made of fine sandstone - compact proportions - sanhara: inner ambulatory - east/west axis: receives direct rays from rising sun - sculpture has harmonious integration w/ architecture - figures sensuous w/ revealing clothes - erotic poses symbolize regeneration"	Lakshmana Temple	
Hindu, Angkor Dynasty. c. 800-1400 CE. Stone masonry, sandstone. - capital of medieval Cambodia built by Suryavarman II - main pyramid surrounded by four corner towers; temple-mountain - corbelled gallery roofs; influenced by Indian used of corbelled vaulting - dedicated to Vishnu; most sculptures represent Vishnu's incarnations - horror vacui of sculptural reliefs - sculpture in rhythmic dance poses; repetition of shapes - complex built by successive kings installing various deities in complex - mixed Buddhist/Hindu character - kings often identified themselves w/ gods they installed - mountain-like towers symbolize five peaks of Mount Meru, sacred mountain said to be center of spiritual and physical universe in Buddhism and Hinduism	Angkor, the temple of Angkor Wat, and the city of Angkor Thom	
- story from Hindu religion - Churning of the Ocean of the Stars to obtain Amrita, nectar of immortal life - both gods (devas) and devils (asuras) churn ocean to guarantee themselves immortality - to churn ocean, used Serpent King, Vasuki - bas-relief at Angkor War depicts devas and asuras churning Ocean of Milk - Vishnu wraps serpent around Mount Mandara; mountain rotates around the sea and churns it	Churning of the Ocean of Milk (from Angkor Wat)	
- most famous and powerful Khmer monarch - heavily influenced by two wives, who were sisters; married one after the other's death - patron of Angkor Thom - devoted to Buddhism although monuments show mixture of Buddhism and Hindu iconography	Jayavarman VII (from Angkor Wat)	
Nara, Japan. Various artists, including sculptors Unkei and Keikei, as well as the Kei School. 743 CE; rebuilt c. 1700 CE. Bronze and wood (sculpture); wood with ceramic-tile roofing (architecture). - Great Eastern Temple, refers to its location on eastern edge of Nara, Japan - noted for colossal sculpture of seated image of Vairocana Buddha - temple and BUddha has been razed several times during military unrest - seven external bays on facade - influenced by monumental Chinese sculptures - largest wooden building in world	Todai-ji	
- one on either side of gate - complex joined woodblock construction - intricate swirling drapery - fierce forbidding looks and gestures - masculine, frightening figures, which protect the Buddha	Nio Guardian Figures (from Todai-Ji)	
"- monumental feat of casting - emperor Shomu embraced BUddhism and erected sculpture as way of stabilizing Japanese population during time of economic crisis - largest metal statue of Buddha in world - mudra: right hand means ""do not fear""; left hand means ""welcome"""	Great Buddha (from Todai-Ji)	
- nandaimon: great south gate, w/ five bays --> three central bays for passing, two outer closed - two stories same size; unusual in Japanese architecture (usually upper floor smaller) - deep eaves supported by six-stepped bracket complex, which rise in tiers w/ no bracketed arms - roof supported by huge pillars - unusual in that has no ceiling; roof exposed from below  - overall effect of proportion and statlines	Great South Gate (from Todai-Ji)	
Kyoto, Japan. Muromachi period, Japan. c. 1480 CE; current design most likely dates to the 18th century CE. Rock garden. - garden as microcosm of nature zen dry garden: - garvel acts as water; gravel raked in wavy patterns - rocks mountain ranges - meant to be viewed from veranda in nearby building - fifteen rocks arranged in three groups - interpreted as islandins in floating sea; mountain peaks above clouds; constellations in sky - from no viewpoint is entire garden viewable at once - focus for meditation - asymmetrical arrangement - bounded by two sides by low, yellow wall wet garden: - contains tea house - seemingly arbitrary in placement, plants actually placed in highly organized and structure environment symbolizing natural world - water symbolizes purification; used in rituals	Ryoan-ji	
Kamakura period, Japan. c. 1250-1300 CE. Handscroll (ink and color on paper). - painted 100 years after civil war depicted in scene - elevated viewpoint - strong diagonals emphasizing movement and action - swift active brushstrokes - narratives read right to left as scroll is unrolled - depersonalized figures, many w/ only one stroke for eyes, ears, mouth - tangled mess of forms accentuated by Japanese armor - lone archer leads escape from burning place w/ equestrian Japanese commander behind - military rule in Japan from 1185 on had an interest in code of warrior; reflected in large quantity of war-related literature and paintings - unrolls like film sequenced; as one unrolls, time advances - burning at imperial palace of Sanjo in Kyoto as rebel forces try to seize power by capturing emperor - coup staged in 1159 as Emperor Go-Shirakawa taken prisoner - imperial palace in flames; rebels force emperor to board a can waiting to take him into captivity - rebels kill those opposed and place their heads on sticks and parade them as trophies	Night Attack on the Sanjo Palace	
"Ogata Korin. c. 1710- 1716 CE. Ink, watercolor, and gold leaf on paper. - Japanese rinpa style named for Ogata (Rin for ""Ko-rin"" and pa meaning ""school"") - influenced by yamato-e style of painting - stream cuts rhythmically through scene; swirls in paint surface indicate water currents - white plum blossoms on left; red on right - tarashikomi technique"	White and Red Plum Blossoms	
Katsushika Hokusai. 1830-1833 CE. Polychrome woodblock print; ink and color on paper. - first time landscape major theme in Japanese prints - last of a series of prints called Thirty-Six Views of Mount Fuji - personification of nature, seems intent on drowning figures in boats - Mount Fuji, sacred mountain to Japanese, seems to be one of the waves - striking design contrasts water and sky w/ large areas of negative space	Under the Wave off Kanagawa (Kanagawai oki nami ura), also known as the Great Wave, from the series Thirty-six Views of Mount Fuji	
. Beijing, China. Ming Dynasty. 15th century CE and later. Stone masonry, marble, brick, wood, and ceramic tile. - largest and most complete Chinese architectural ensemble in existence - 9000 rooms - walls 30 feet high to keep people out and those inside in - named b/c only royal court could enter - each corner of rectangular plan w/ tower representing four corners of the world - focus: Hall of Supreme Harmony, throne room and seat of power; wood structure made w/ elaborately painted beams; meant for grand ceremonies - yellow tile roofs and red painted wooden beams placed on marble foundations unify structures in artistic whole - Hall of Supreme Harmony ceremonies: new year, winter solstice, emperor's birthday - surrounding wall characteristic of Chinese city: privacy w/in provides protection; containment part of Chinese culture	Forbidden City	
Han Dynasty, China. c. 180 BCE. Painted silk. - died 168 BCE in Hunan province; Han Dynasty - tomb found w/ over 100 objects in 1972 - T-shaped silk banner covering inner coffin of intact body - probably carried in procession to tom then placed over body to speed journey to afterlife - yin symbols at left; yang symbols at right; center mixes the two philosophies - painted in three distinct regions - top: heaven w/ crescent moon at left, legend of ten suns at right; center: two seated officers guard centrance to heavenly world - middle: earth w/ Lady Dai in center on white platform about to take journey to heaven w/ walking stick that was found in her tomb; mourners and assistants appear by side; dragons' bodies symbolically circled through bi in yin and yang exchange - bottom: underworld; symbolic low creatures frame underworld scene: fish, turtles, dragon tails; tomb guardians protect the body	Funeral Banner of Lady Dai (Xin Zhui)	
** Fan Kuan. c. 1000 CE. Ink and colors on silk. - artist isolated self away from civilization to be w/ nature and study it, for landscapes; Daoist philosophy - produced very complex landscapes - different brushstrokes describe different kinds of trees; coniferous, deciduous, etc. - long waterfall on right balanced by mountain on left; waterfall accents height of mountain - mot pure landscape: donkeys laden w/ firewood driven by two men; small temple in forest; man seen as small and insignificant in vast natural world - mists created by ink washes; silhouette roofs of temple - might be only surviving work; signature hidden in bushes on lower right	Travelers among Mountains and Streams	

** Imperial Bureau of Painting. c. 15th century CE. Hanging scroll (ink and color on silk). - Korean prime minister and soldier - made when he was a second grade civil officer; insignia designed w/ clouds and wild goose - Korean portraits emphasize how the subject made a great contribution to country and how spirit of loyalty to king and country valued by Confucian philosophy - repainted over the years, especially in 1475 - great scholar	Portrait of Sin Sukju (1417-1475)	

** Artist unknown; based on an oil painting by Liu Chunhua. c. 1969 CE. Color lithograph. - painted during Cultural Revolution of 1966-1976; high art dismissed as feudal or bourgeois - poster-like; vivid colors, dramatic and obvious political message - dominated by pictorial representation - done anonymously; individual artistic fame seen as counter-cultural in collectivist society - moment in 1920s; Mao on way to Anyuan to lead miners' strike - Mao worked for reforms for miners; supported a local strike for better wages, working conditions, education - for many people: this action formed permanent bond w/ Communist party - iconic representation of Great Leader's career - may be most reproduced image ever made: 900,000,000 copies generated	Chairman Mao En Route to Anyuan	
Qin Dynasty. c. 221-209 BCE. Painted terra cotta. - about 8000 terracotta warriors, 100 wooden chariots, 2 bronze chariots, 30,000 weapons buried as par of tomb of Emperor Shi Huangdi - soldiers 6 feet tall, some fierce, some proud, som confident; taller than average person of the time - representation of a CHinese army marching into next world - Daoism in individualization of each solider despite their numbers - originally colorfully painted - discovered in 1974 - warriors mass produced, then personalized	Terra cotta warriors from mausoleum of the first Qin emperor of China	

** Luoyang, China. Tang Dynasty. 493-1127 CE. Limestone. - caves along banks of Yi River - sculptures and reliefs carved from existing rock; some colossal, some small - documents attests that 800,000 people worked on the site; 110,000 Buddhist stone statues, more than 60 stupas, 2800 inscriptions on steles - Buddha arranged as if on altar of a temple, deeply set into rock face - inscription states that Empress Wu Zetian was principal patroness of site and used private funds to finance - Vairocana Buddha having monk attendants, bodhisattvas, and guardians flanking - elongated legs and exaggerated poses
Longmen Caves	

** Three Kingdoms period, Silla Kingdom, Korea. Fifth to sixth century CE. Metalwork - uncovered in Gyeongju, Korean from a royal tomb - symbolizes geometric trees - antler forms influenced by Shamanistic practices in Siberia - very light weight; gold extremely thin and fragile; had limited use; maybe for ceremonial occasions, perhaps only for burial	Gold and jade crown	

** "Yuan Dynasty, China. 1351 CE. 
White porcelain with cobalt-blue underglaze. - one of most important examples of blue and white porcelain in existence - made for altar of Daoist temple, along w/ incense burner, which as not been found; typical altar set - dedication on side of neck of vessels; believed to be earliest known blue and white porcelain dedication - inscription on one of vase: ""Zhang Venjin, from Jingtang community, Dejiao village, Shuncheng township, Yushan county, Xinzhou circuit, a disciple of the Holy Gods, is pleased to offer a set comprising one incense burner and a pair of color waves to General Hu Jingyi at the Original Palace in Xingyuan, as a prayer for the protection and blessing of the whole family and for the peace of his sons and daughters. Carefully offered on an auspicious day in the Fourth Month, ELeventh year of the Zhizheng reign."" - blue color imported from Iran; Chinese expansion into western Asia makes cobalt blue available - vases modeled after bronzes - elephant-head-shaped handles - neck and foot of vases: leave and flowers - central section: Chinese dragons w/ traditional long bodies and beards; dragons have scales and claws set in a sea of clouds - named after Sir Percival David, collector of Chinese art"	The David Vases	

"Bichitr. c. 1620 CE. Watercolor, gold, and ink on paper. - Jahangir had many artists to follow him wherever he went; wanted everything recorded - sought to bring together things from distant lands - seated on hourglass throne; sands to time run out; Jahangir near the end - surrounded by halo of sun and moon; Jahangir source of all light - sits on Renaissance carpet; figures of small cherubs copied from European paintings - artist in lower left corner; symbolically signs name on footstool beneath Jahangir; holds miniature w/ two horses and en elephant ---> gifts from patron? - James I of England in lower left corner - Ottoman sultan (not a real portrait) - Holy Man handed book by Jahangir (or other way around?); placed above and ranks higher than all others - quotation: ""though outwardly shahs stand before him, he fixes his gazes on dervishes"""	Jahangir Preferring a Sufi Shaikh to Kings	

Pohnpei, Micronesia. Saudeleur Dynasty. c. 700-1600 CE. Basalt boulders and prismatic columns. - ancient city that acted as capital of Saudeleur Dynasty of Micronesia - 92 small artificial islands connected by canals, about 170 acres in total - built out into water on a lagoon; similar to Venice, Italy - seawalls act as breakwaters; fifteen feet high, thirty-five feet thick - canals flushed clean w/ tides - islands arranged SW to NE to take advantage of trade winds - city built to seperate upper classes from lower classes - king arranged for upper class to live close to him, to keep an eye on them - curved outer walls point upward at edges, giving complex symbolic boat-like appearance	Nan Madol	

** Nukuoro, Micronesia. c. 18th to 19th century CE. Wood. - many kept in religious buildings belonging to community - represent individual deities - sometimes dressed in garments; may have been decorated w/ flowers - simple geometric forms - erect pose; long arms; broad chest - chin drawing to a point; no facial features - horizontal lines used to indicate knee caps, vael, waistline	


** Female deity	

** Marshall Islands, Micronesia. 19th to early 20th century CE. Wood and fiber. - Marshall Islands low-lying and hard to see from a distance - charts composed to steer through the many islands to get to a destination - horizontal and vertical sticks support chat - diagonal lines indicate water/wind currents - small shells indicate position of islands on chart - chart made of wood: waterproof and buoyant - meant to be memorized before a voyage; not necessarily used during	Navigation chart	

** Hawaiian.
 Late 18th century CE. Feathers and fiber. - coat made of thousands of bird feathers; worn by men - 500,000 feathers; some birds only had seven usable feathers - red considered royal color in Polynesia - coconut fiber used as base; feathers tied to it - cloak created by artist who chanted wearer's ancestors to imbue their power on it - protected wearer from harm	'Ahu 'ula (feather cape)	

** Rarotonga, 
Cook Islands, central Polynesia. Late 18th to early 19th century CE. Wood, tapa, fiber, and feathers. - large column-like wooden shaft placed upright in a village common - large head placed on top; several smaller heads carved below it - shaft in form of elongated body - central carved wooden shaft around which roll of tapa placed - soul of god represented by polished pearl shells and red feathers that are placed inside bark cloth next to interior shaft - most staff gods destroyed, only top ends retained as trophies - contextual image: staff gods thrown don in village square in front of European-style church; represents fall of one faith and adoption of another	Staff god	

** "Niue. c. 1850-1900 CE. 
Tapa or bark cloth, freehand painting. - hiapo = ""tapa"" or ""bark cloth"" - using stencils, artists dye exposed parts of tapa w/ paint - after tapa is dry, designs sometimes repainted to enhance effect - traditionally worn as clothing before importation of cotton - tapa take on special meaning: commemorating an event; honoring a chief; noting a series of ancestors - each set of designs meant to be interpreted symbolically; many of images have rich history"	Hiapo (tapa)	

** Gottfried Lindauer. 1890 CE. 
Oil on canvas. - New Zealand painter, famous of portraits of Maori chieftains - journeyman painter-tradesman who worked on commission - subject: Tamati Waka Nene (c. 1780-1871), Maori chief and convert to Wesleyan faith - painting posthumous based on photograph by John Crombie - emphasis on symbols of rank: elaborate tattooing, staff w/ eye in center, feathers dangling from staff	Tamati Waka Nene	

** New Ireland Province, 
Papua New Guinea. c. 20th century CE. Wood, pigment, fiber, and shell. - Malagan ceremonies send souls of deceased on their way to otherworld - sometimes ceremonies begin months after death and can last extended period of time - ceremonies free of living of obligation of serving the dead - erect structures suited to purpose; after ceremony structures considered useless; usually destroyed or allowed to rot - sculptures of deceased commissioned; represent individual's soul/life force, not physical presence - extremely intricate in their carving - indicates relationship of particular deceased person to a clan, and living members of the family - large hair comb reflects a hairstyle of the time - painted black, yellow, and red: important colors denoting violence, war, magic	Malagan mask and display	

** Torres Strait. Mid- to late 19th century CE.
 Turtle shell, wood, fiber, feathers, and shell. - Torres Strait water passageway between Australia and New Guinea - turtle masks unique to this region - used w/ grass costumes in ceremonies about death, fertility, or male initiation - ceremonies involved fire, drum beats, and chanting; recreating mythical ancestral beings and their impact on these people in everyday activities - some masks combine human and animal forms; this mask shows bird placed on top	Buk (mask)	

** Fiji, Polynesia. 1953 CE. 
Multimedia performance (costume; cosmetics, including scent; chant; movement; and pandanus fiber/hibiscus fiber mats), photographic documentation. - enormous tapa cloth made for visit of Queen Elizabeth II in 1953, on occasion of her coronation as Queen of England - presentation of Queen example of performance art - imagery of royal crowns, geometric patterns, and a floral motifs - men oversee growth of mulberry trees that produce the tapa; women turn bark into cloth - after tapa pounded to create pieces of cloth, edges of smaller pieces then glued/felted together to produce large sheets - decorated according to local tradition: sometimes stenciled, sometimes printed/dyed	Presentation of Fijian mats and tapa cloths to Queen Elizabeth II	

** "Rapa Nui (Easter Island). 
c. 1100-1600 CE. 
Volcanic tuff figures on basalt base. - about nine hundred statues in all, mostly male, almost all facing inland, fifty tones apiece - erected on large platforms of stone mixed w/ ashes from cremations; platforms as sacred as statues on them - images represent personalities deified after death, or commemorated as first settler-kings - prominent foreheads, large broad noses, thin pouting lips, ears that reach top of heads - short thin arms falling straight down; hands across lower abdomen below navel - chests and navels delineated - topknots added to some statues - white coral placed in eyes to ""open"" them"	Maoi on platform (ahu)	

** "Spain. Frank Gehry (architect). 1997 CE. 
Titanium, glass, and limestone. - Canadian-American architect based in Los Angeles - swirling forms and shapes mark a contract w/ industrial landscape of Bilbao - from river side, building resembles a boat, referencing the Bilbao's past as a shipping and commercial center - curving forms designed by computer software program called Catia - fixing clips make shallow dent in titanium surface; effect of having a shimmering surface that changes according to atmospheric conditions - revitalized port area of Bilbao; ""Bilbao effect"" refers to impact that a museum can have on a local economy - appearance of asymmetrical exterior w/ outside walls giving no him to interior spaces - irregular masses of titanium walls - sweeping curved lines - called deconstructivist architecture: architecture that seeks to create a seemingly unstable environment w/ unusual spatial arrangements"	Guggenheim Bilbao Museo	

** Rome, Italy. Zaha Hadid (architect). 2009 CE. Glass, steel, and cement. - Iraqi-born, British-based artist - two museums (MAXXI Art and MAXXI Architecture), a library, auditorium, and cafeteria - internal spaces covered by glass roof; natural light admitted into interior, filtered by louvered blinds - walls flow and melt into one another, creating new and dynamic interior spaces - constantly changing interior/exterior views - transparent roof, modulate natural light	MAXXI National Museum of XXI Century Arts	

** "New York City, U.S. Christo and Jeanne-Claude. 1979-2005 CE. Mixed-media installation. - Christo Bulgarian born; Jean-Claude of French descent, born in Morocco - 7503 ""gates"" of free-hanging saffron colored fabric panels - framed all pathways in Central Park, New York City - 16 feet tall gates formed continuous river of color - covered 23 miles of footpaths - temporary installation, left for sixteen days - after exhibition closed, materials recycled"	The Gates	

** Washington, D.C., U.S. Maya Lin. 1982 CE. Granite. - artist Ohio-born Chinese-American - V-shaped monument cut into earth w/ 60,000 casualties of Vietnam War listed in order killed or reported missing - one arm pointed to Lincoln Memorial, other to Washington Monument - black granite highly reflective surface so that viewers can see themselves in the names of the veterans; black appropriate somber color for memorial - strongly influenced by Minimalist movement - contest for memorial design; some backlash when it was revealed Asian person won	Vietnam Veterans Memorial	

** "Jean-Michel Basquiat. 1983 ce. Acrylic and oil paintstick on three canvas panels. - artist born in Brooklyn, New York, of Puerto Rican and Haitian parents; rebelled against middle class upbringing he was born into - some traditional forms: triptych, canvas, oil paint - modernist expression: influence of graffiti art - flattened darkened background; flat patches of color; thick lines - glorifies African-American musicians: salute to Jazz musicians Charlie Parker and DIzzy Gillespie in either wing - heads seem to float over outlined bodies and dissolve as you go down body - focus on contrast and juxtaposition, not on balance/scale - words are those attributed to musicians (ornithology misspelled; reference to Charlie ""The Bird"" Parker)"	Horn Players	

** "Song Su-nam. 1983 CE. Ink on paper. - Korean artist using traditional ink on paper - large vertical lines of various thickness - subtle tonal variations of ink wash - one of leaders of ""Sumukhwa"", a new type of ink paintings 1980s; ink painting traditional form of artistic expression in Korea; this movement revitalizes ink painting in modern context"	Summer Trees	

** Magdalena Abakanowicz. 1985 ce. Burlap, resin, wood, nails, and string. - Polish artist - since 1974, artist makes figures often w/o heads/arms in large groups singly - figures sit on low stretcher of wooden legs, substituting for human legs - figure hollowed out, just a shell, hardened fiber casts made from plaster molds - figure placed to be seen in the round: complete back, the hollow front - hardened figure has appearance of crinkled human skin set in earth tones	Androgyn III	

** "Xu Bing. 1987-1991 CE. Mixed-media installation. - Chinese-born artist; US resident - original title: ""An Analyzed Reflection of the End of This Century"" - original in National Museum of Fine Arts in Beijing; filled a large exhibition space - 400 handmade books placed in rows on ground - one walks beneath fifty printed scrolls, which hang from the ceiling - uses traditional Asian woodblock techniques - many of Chinese characters inventions of artist and have no meaning - artist lost favor w/ Communist government over this work - criticized as ""bourgeois liberation"" and it was claimed that its meaninglessness hid secret subversions"	A Book from the Sky	

** "Jeff Koons. 1988 CE. Glazed porcelain. 
- Pennsylvania-born artist, working in New York - work exists as a commentary on celebrity romance, sexuality, commercialism, stereotypes, pop culture, sentimentality - artificially idealized female form: overly yellow hair, bright red lips, large breasts, pronounced red fingernails; overtly fake look - life-size - kitsch - created permanent reality out of something ephemeral and never meant to be exhibited - woman is Jayne Mansfield, a popular screen star - Pink Panther, cartoon character derived from series of American movies - tender delicacy of panther's gesture - part of series called ""The Banality"" at show in Sonnabend Gallery in NY 1988"	Pink Panther	

** Cindy Sherman. 1990 ce. Photograph.
 - New Jersey born, American artist; appears as photographer, subject, costumer, hairdresser, and makeup artist in each work - works comment on gender, identity, society, and class distinction - this series sheds a modern light on great masters - uses old master painting as a starting point, but the works are not derivative - image explores theme of Judith decapitating Holofernes - richness of costuming and setting acts as commentary on late 19th century versions of this subject - richly decorative drapes hang behind figure - Judith lacks any emotional attachment to the murder that has taken place - Holofernes appears mask-like, alert, and nearly bloodless	"Untitled (#228), from the History Portrait series"	

Faith Ringgold. 1991 CE. Acrylic on canvas, tie-dyed, pieced fabric border. - New York-born African-American artist; uses American slave art form of quilt to create works - quilts originally meant to be beautiful and useful; works of applied art; seen as traditionally female art form - combines traditional use of oil paint w/ quilting technique - these quilts not meant to be placed on beds - narrative element - feminist issues dominate - often figures in Ringgold works act out history that might never have taken place, but artist would have liked to take place - fictional character named WIllia Marie Simone, who takes her friend and three daughters to Louvre and dances in front of three paintings by Leonardo Da Vinci	"Dancing at the Louvre from the series The French Collection, Part I; #1"	

"Jaune Quick-to-See Smith. 1992 CE. Oil and mixed media on canvas. - member of Salish and Kootenai American Indian tribes of Flathead Nation - meant as ""Quincentenary Non-Celebration"" of European occupation of North America; response to 500th anniversary of Columbus's voyage to Americas - collage elements and abstract expressionist brushwork - red paint symbolic of shedding of American Indian blood - newspaper clippings, images of conquest placed over large dominant canoe - American Indian social issues caused by European occupation stressed: poverty, unemployment, disease, alcoholism - array of objects sardonically representing Indian culture in eyes of Europeans: sports teams, Indian-style knick knacks like toy tomahawks, dolls, and arrows"	Trade (Gifts for Trading Land with White People)	

** "Emily Kame Kngwarreye. 1994 CE. 
Synthetic polymer paint on canvas. - Australian aborigine artist - simulates color and lushness of ""green time"" in Australia after rains when outback flourishes - dump dot technique using brush to pound color into canvas and create layers of color and movement - four panels, eleven meters wide"	Earth's Creation	

** Shirin Neshat (artist); photo by Cynthia Preston. 1994 CE. Ink on photograph. - Iranian-born artist, raised in US - poem on face written in Farsi; expresses piety - poem by Iranian woman who writes poetry on gender issues - gun divides body into darker and lighter side; adds note of ominous tension in work - Westerners view work as expression of female oppression - Iranians could view work as obedient right-minded woman ready to die defending her faith and customs - black and white photograph	Rebellious Silence, from the Women of Allah series	

** "Pepon Osorio. 1994 CE.
 Mixed-media installation. - Puerto Rican-born artist living in New York - large installation recreating center of Latino male culture: barbershop - challenges viewer to question issues of identity, masculinity, culture, attitudes - interior of barbershop in which ""no crying is allowed"" -- masculine attribute - photos of Latino men on walls - video screens on headrests depict men playing, a baby being circumcised, men crying - appropriately tacky and grimy setting - kitsch items used everywhere as symbols of consumer culture"	En la barbería no se Llora (No Crying Allowed in the Barbershop)	
** Michel Tuffery. 1994 CE. Mixed media. - 
artist born in New Zealand of Samoan, Cook Islands, and Tahitian descent - interest in Polynesian heritage - life-size sculpture of bull made from flattened cans of corned beef - canned corned beef a favorite food in Polynesia; exported from New Zealand - canned meat (pisupo) given as gifts on special occasions in Polynesia; major contributor to Polynesian obesity - introduction of canned meat caused fall in traditional cultural skills of fishing, cooking, agriculture - static sculpture w/ small concealed wheels at feet for ease of movement - theme of recycling emphasized by reuse of these cans - two motorized bulls often engage in multi-media performance art called The Challenge	Pisupo Lua Afe (Corned Beef 2000)	
** Nam June Paik. 1995 CE. 
Mixed-media installation (49-channel closed-circuit video installation, neon, steel, and electronic components). - Korean-born artist who lived in New York City; intrigued by maps and travel: neon outlines symbolize multicolored maps for each state; fascination w/ interstate highway system; neon symbolizes motel and restaurant signs - neon lighting outlines fifty states and District of Columbia (Alaska and Hawaii on side walls) - each state w/ separate video feed; total of 313 monitors - camera turned on to spectator and its TV feed appears on one of monitors; turns spectator into participant in artwork	Electronic Superhighway	
** Bill Viola. 1996 CE. Video/sound installation.
 - born in Queens, New York - promoted video as an art form - video installations are total environments - two channels of color video projections from opposite sides of large dark gallery onto two large back-to-back screens suspended from ceiling and mounted to floor; four channels of amplified stereo sound, four speakers - two channels of video projected onto 12 foot tall double-sided screen; on one side, figure approaches from long distance; as he stopes, a small flame appears on his feet and spreads rapidly to engulf him in roaring fire; when subsides, man is gone - on opposite side: when figure stops, stream of water begins to pour on head; quickly turns into raging torrent, inundating the man; when water slows, man is gone - two video screens: free-standing, double-sided projections - fire: flames consum figure of man, beginning at his feet - water: man walks toward viewer and water falls from above - figures walk in extremely slow motion - actions repeat again and again - interested in sense perceptions; same noise plays for both, but seems to fit whichever viewer is watching - implied cycle of purification and destruction - evokes eastern and western spiritual traditions: Zen Buddhism, Islamic Sufism, Christian mysticism	The Crossing	
** Mariko Mori. 1998 CE. 
Color photograph on glass. - Japanese artist; uses creative interpretation of traditional Japanese art forms - romanticized views of popular culture - Mori appears as if in a vision in guise of Heian deity Kichijoten, the essence of beauty and harbinger of prosperity and happiness - holds wish-granting jewel, a nyoi hoju, which has the power to deny evil and fulfill wishes - jewel symbolizes Buddha's universal mind - animated figures of lighthearted aliens play musical instruments on clouds - merging of consumer entertainment fantasies w/ traditional Japanese imagery - dead sea salty --> Shintoism: salt as purification agent - Buddhist lotus - toy in back resembles Tibetan stupa	Pure Land	
** Kiki Smith. 2001 CE. 
Ink and pencil on paper. - American artist, born in Germany, lives in New York City - nude female figure; theme of Smith's work is human body - large wrinkled drawing, pinned to a wall; reminiscent of table cloth or bed sheet - female strength emphasized in woman lying down w/ wild beast - wolf seems to be tamed by woman's embrace - wolf seen as traditionally evil/dangerous symbol, but not here	Lying with the Wolf	
** Kara Walker. 2001 CE. 
Cut paper and projection on wall. - California-born, New York-based, African American artist - technique: draws images w/ greasy white pencil or soft pastel crayon on large pieces of black paper; cuts paper w/ knife; images adhered to gallery wall w/ wax; traditional silhouette forms; overhead projectors throw colored light onto walls, ceilings, floor; cast shadows of viewer's body that mingle w/ black paper images - exploration of African-Americans in antebellum South: tennager holds flag that resembles colonial ship sail; one man has leg cut off; woman aborting a child; woman caring for newborns - viewer interacts w/ work, walking around it, engaging in elements of it; we are part of the history of piece	Darkytown Rebellion	
** Yinka Shonibare. 
2001 CE.
Mixed-media installation. - a
rtist British born of Nigerian descent; lives and works in London - life-size headless mannequin; guillotined by French Revolution - European-style dress made of African print fabric (batik); represents colonialism and relationship between Europe and Africa - flowering vines cast to floor - two men in Fragonard painting not included; audience takes place of the men; erotic voyeurism	
** The Swing (after Fragonard)	
El Anatsui.
2003 CE.
Aluminum and copper wire.
- artist born in Ghana, spent much of career in Nigeria - 1000 drink tops joined by wire to form cloth-like hanging - bottle caps from distillery in Nigeria - power tools, like chainsaws and welding torches - converts found materials in new type of media that lies someplace between painting and sculpture - recycling of found objects - colorful textured wall hangings; relates to Western African textiles - combines aesthetic traditions of home country, adopted country, and global art movement of abstract art	Old Man's Cloth	

** Julie Mehretu. 2004 CE. 
Ink and acrylic on canvas.
- born in Ethiopia, lives and works in NYC - paints large scale paintings - although paintings done w/ abstract elements, titles allude to meaning - stylized rendering of stadium architecture - forms suggest excitement, almost frenzy of competition held in circular space surrounded by international images - dynamic competition suggested in sweeping lines that create vibrant pulse - uses multi[layered lines to create animation in work - sweeping lines to create depth, focus of attention around large central core from which colors, icons, flags, and symbols resonate	Stadia II	

** "Wangechi Mutu. 2006 CE. 
Mixed media on Mylar. - Kenya-born, New York-based artist - collaged female figures composed of human, animal, object, and machine parts - commentary on female persona in art history - cyborg - reclines in relaxed position - green snake interlocks w/ fingers; bird feathers in back of head - left ear lobe has chicken feet, insect legs, and pinchers - blotched skin - ironic twist on praying mantis: suggests religious rituals; mantis means ""prophet"" in Greek; insects use camouflage; this figure seems camouflaged"	Preying Mantra	

** Doris Salcedo. 2007-2008 CE. 
Installation. - Colombian sculptor - installation that features large crack that begins as hairline and widens to two feet in depth - floor of museum opened and a cast of Columbian rock faces inserted - stresses interaction between sculpture and space - Shibboleth meant to exclude people from joining a group - crack emphasizes gap in relationships; reminder of disruption in spaces - references racism and colonialism; keeping people away or separating them - installation now sealed, but exists as a scar, commemorates life of underclasses	Shibboleth	

** Ai Weiwei. 2010-2011 CE. 
Sculpted and painted porcelain. - Chinese artist - installation containing millions of individually handcrafted ceramic pieces resembling sunflower seeds - symbolically represent ocean of fathomless depth; each seed made in Jingdezhen, city known for porcelain production Imperial China - 600 artisans worked for two years, each seed hand-painted - sunflower seeds eaten as source of food during famine era under Mao Zedong - ideology of Chairman Mao: he was the sun, followers seeds - originally installation walkable, but raised harmful ceramic dust, viewing then limited to sidelines	Kui Hua Zi (Sunflower Seeds)	

** Master sculptor Vulca. c. 510- 500 BCE. 
Original temple of wood, mud brick, or tufa (volcanic rock); terra cotta sculpture. - little architecture survives; this model drawn from descriptions by Vitruvius - steps directly in front of deep porch; entrances emphasized - influences of Greek architecture in columns and capitals; columns unfluted, made of wood - Tuscan order - raised on a podium - three doors represent three gods; division of interior into three spaces - statue of Apollo placed on roof instead of cella - only foundation remain	Temple of Minerva	

** Tarquinia, Italy. Etruscan. c. 480-470 BCE. 
Tufa and fresco. - named after a triclinium - banqueting couples recline, eating in ancient manner - men painted in darker colors than women - trees spring up between main figures; shrubbery grows between reclining couches; suggests rural setting? - maybe funeral banquet intended; emotions of celebration - ceiling w/ polychrome checkerboard pattern; circles may symbolize time - dancing figures play musical instruments in festive celebration of the dead	

Tomb of the Triclinium	

** Etruscan. c. 520 BCE. Terra cotta.
 - of married couple, whose ashes were placed inside - full-length portraits - both once held objects in hands (drinks or egg (symbolize afterlife)?) - attention on upper half of figures - unrealistic L-turn to legs - ancient tradition of reclining while eating;represents a banquet couch - man w/ protective gesture around woman; woman feeds man - broad shoulders; little anatomical modeling - made in 4 pieces and joined together - inclusion of woman suggests Etruscan society egalitarian	Sarcophagus of the Spouses	
- one of four large figures that once stood on roof of Temple of Minerva; depicted labors of Hercules - meant to be seen from below - archaic smile - may have been carved by Vulca of Veii (most famous Etruscan sculpture of the age) - strides forward - idealized, well-muscled body	Apollo from Veii (from Temple of Minerva)	

** Pompeii, Italy. Imperial Roman. c. second century BCE; rebuilt c. 62-79 CE. Cut stone and fresco. 
- owned by two brothers; both freedmen who made money as merchants - narrow entrance sandwiched between several shops - atrium open to sky w/ impluvium in center; cubicula radiate around - peristyle garden in rear w/ fountain, statuary, and more cubicula; private area of house - axial symmetry; someone entering can see all the way through to peristyle garden in rear - exterior of house w/o windows; interior lighting comes from atrium and peristyle	House of the Vettii	

Rome, Italy. Imperial Roman. 70-80 CE. Stone and concrete. - accommodated 50,000 spectators - concrete core; brick casing; travertine facing - 76 entrances and exits circle facade - interplay of barrel vaults, groin vaults, arches - meant for wild/dangerous spectacles (gladiator combat, animal hunts, naval battles) but not religious persecution - facade uses engaged columns: first story Tuscan, second Ionic, third Corinthian, top flattened Corinthian; each thought of as lighter than order below - above squared windows at top level: small brackets meant to hold flagstaffs; anchors for retractable canvas roof used to protect crowd on hot days - much of marble pulled off during Middle Ages	Colosseum (Flavian Amphitheatre)	

. Rome, Italy. Apollodorus of Damascus. Forum and markets: 106-112 CE; column completed 113 CE. Brick and concrete (architecture); marble (column). - built w/ booty collected from Trajan's victory over Dacians - large central plaza flanked by stoa-like buildings on each flank - originally held equestrian monument dedicated to Trajan in center - part of complex that included Basilica of Ulpia, the Markets of Trajan, and the Column of Trajan	
Forum of Trajan	
- 385 ft by 182 ft, w/ 2 apese; grand interior space - nave spacious and wide - double 
colonnaded side aisles - second floor had galleries or maybe clerestory windows - timber roof 80 feet across - law courts held here; apses were a setting for judges - said to have been paid by Trajan's spoils taken from defeat of Dacians - Ulpius was Trajan's family name	Basilica of Ulpia (from Forum of Trajan)	
- original had 150 shops - multilevel mall - semicircular building held several levels of shops - main space groin-vaulted; barrel-vaulted shops	Market of Trajan (from Forum of Trajan)	

** "Imperial Roman. 118-125 CE. 
Concrete with stone facing. - dedicated to every major deity - inscription: ""Marcus Agrippa, son of Lucius, having been consul three times, built it"" - Corinthian capital porch in front of building - facade w/ two pediments, one deeply recessed behind the other - square panels in floor and in coffers contrast w/ roundness of walls; coffers may have been filled w/ bronze rosette designs to simulate stars - cupola walls enormously thick: 20 feet at base - oculus 27 feet across: allows for sunlight and air; acts as moving spotlight across interior - height of building equals width; interior based on the circle - walls have 7 niches for statues of the gods and represent 7 planets - walls thenned at top; coffers take some pressure off - triumph of concrete construction - brilliantly decorated - originally had large atrium in front and built on high podium; modern Rome has risen up to it - large open space to accommodate many people"
	Pantheon	

- triclinium: dining room in a Roman house - main scene death of Greek hero Pentheus - Pentheus opposed to cult of Bacchus and was torn to pieces by women (including mother) in Bacchic frenzy; two women pulling at his hair in this image - architecture seen through painted windows; imaginary landscape	Pentheus Room (from House of the Vettii)	

** Republican Roman. c. 75-50 BCE. Marble. - extremely realistic face (veristic portrait) - bulldog-like tenacity of features; overhanging flesh; deep crevices in face - full experience and wisdom - features may have been exaggerated by artist to enhance adherence to Republican virtues - busts mostly of men, depicted as elderly	Head of a Roman Patrician	

Imperial Roman. Early first century CE. Marble. - idealized - contrapposto - confusion 
between god and man intentional; sense of divine rule - standing barefoot indicates he is on sacred ground - breastplate number of gods participating in return of Roman standards from the Parthians - breastplate indicates he is a warrior; judge's robes show him as a civic ruler - back not carved; meant to be placed against a wall - characteristic of Augustus: part in hair over left eye and two locks over right - may have carried sword, pointing down, in left hand - right hand in Roman orator pose - at base: Cupid at back of dolphin; reference of Augustus's divine descent from Venus - found in Villa of Livia (Augustus's wife)	Augustus of Prima Porta	
- burial chamber of Trajan (ashes placed in base) - stood amid Trajan's Forum - 128-feet high, 625 foot narrative cycle wrapped around - told story of Trajan's defeat of the Dacians - 150 episodes; 2500 figures; 23 registers; continuous narrative - crowded composition - low relief, few shadows to cloud what must have been very difficult object to view in entirety - scholarly debate over how meant to be viewed - meant to be entered; visitor wander up interior spiral staircase to viewing platform - topped by heroic nde statue of Trajan; now replaced by St. Peter - view would impress visitor w/ Trajan's accomplishments, including forum and markets - two Roman libraries containing Greek and Roman manuscripts flanked - also includes mundane activities	Column of Trajan (from Forum of Trajan)	

** Late Imperial Roman. c. 250 CE.
 Marble. - extremely crowded surface w/ figures piled on top of one another - each figure lacks individuality - confusion of battle echoed by congested composition - Roman army trounces bearded and defeated barbarians - youthful Roman general appears center top w/ no weapons; only Roman w/ no helmet (indicates he is invincible and needs no protection) - Rome at war throughout third century - writhing figures - emotional expressionism	Ludovisi Battle Sarcophagus	

** Archaic Greek.
 c. 530 BCE. Marble with remnants of paint. - grave marker, replacing huge vases of the Geometric period - general representation of ideal warrior - rigidly frontal; nude - arms and legs largely cut free from stone - freestanding w/ legs appearing to stride forward - hair knotted and falls in neatly braided rows down the back - eyes wide open; squarish shoulders - face masklike - named after young military hero Kroisos; inscription at base identifies him - some paint survives - archaic smile - strong Egyptian influence but softer features	Anavysos Kouros	

** Archaic Greek. 
c. 530 BCE. Marble, painted details. - broken hand fitted into socket; probably held an attribute - may have been goddess - tightened waist - breasts revealed beneath drapery - so=called b/c named for peplos - rounded and naturalistic face - much of paint reminds; animates face and hair - hair falls naturally beside body	Peplos Kore from the Acropolis	

** Polykleitos. Original 450-440 BCE.
 Roman copy (marble) of Greek original (bronze). - contrapposto - blocklike solidity - broad shoulders, thick torso, muscular body - warrior and athlete - hand once held a pear - averts gaze; may admire him, but he does not recognize it - found in Pompeii in a place for athletic training - also referred to as The Canon - tense and relaxed limbs oppose each other diagonally	Doryphorus (Spear Bearer)	

** - Parthenon sculptures, 
also called the Elgin Marbles - east pediment of the Parthenon - shows birth of Athena from the head of Zeus; other deities watching - two seated figures goddesses Demeter and Persephone - sculptures comfortably sit in triangular space of pediment - classical art; contrapposto	Helios, Horses and Dionysos (from the Acropolis)	

- scene from the Panathenaic Frieze depicting the Panathenaic Procession, held every four years to honor Athena - first time in Greek art showing depiction of human event on temple - higher up relief placement, more 3D relief was cared (in order to be seen better from below) - procession began at Dipylon Gate, passed through agora, ended at Parthenon - Athenians placed new peplos on statue of Athena - Six Ergastines (young women in charge of weaving Athena's peplos) greeted by two priests - Isocephalism - new theory: not Panathenaic Procession, but story of legendary Athenian king, Erechtheus, who sacrificed on of his daughters to save city of Athens; told to do so by Oracle of Delphi - elevated Athenian citizens almost to stature of gods	Plaque of the Ergastines (from the Acropolis)	
- graceful winged figure modeled in high relief - deeply incised drapery lines reveal body, wet drapery - awkward ungainly pose --> graceful dance step - representative of sculptors looking for unexplored ways to use human figure as expressive medium	

** Victory Adjusting Her Sandal (from the Acropolis)	
Attributed to Kallimachos. c. 410 BCE. Marble and paint. - classical work - erected in Dipylon cemetery in Athens - commemorates death of Hegeso; inscription identifies her and her father - genre scene: woman examining piece of jewelry from jewelry box handed to her by standing servant; may represent her dowry - jewelry painted in, not visible - Hegeso's status shown in her foot being on base of chair, not ground	Grave Stele of Hegeso	

** Hellenistic Greek.
D: c. 190 BCE. 
M: Marble. - 
meant to stand in/above fountain cascading water around rocks below OR adorn bow of a stone ship - wet drapery look imitates water on wet body - evidence of invisible wind on body - dramatic twist and contrapposto of torso - monumentality of figure - missing right arm may have raised victory crown or held open hand in greeting - boat at base battleship w/ oarboxes and traces of a ram - probably built to commemorate navel victory in 190 BCE - goddess of victory; job to spread message of victory - found in 1863 in situ on Samothrace	
Winged Victory of Samothrace	
- gigantomachy; giants (as helpless tools) dragged up the stairs to worship the gods - gods' victory over giants parallels Alexander the Great's defeat of the Persians - deeply carved figures overlap one another; masterful handling of spatial illusion - dramatic intensity of figures, movement; heroic musculature - Athena grabs Alkyneos by hair and drags him up stair to worship Zeus - Nike on right crowns Athena in victory - Gaia (earth goddess) looks on in horror and pleads for the fate of the giants (her sons) - figures dominate space	Athena (from Pergamon)	

Hellenistic Greek. c. 100 BCE. Bronze. - may have been part of a group; maybe single sculpture w/ head turned to face unseen opponent - older man, pas his prim - mostly defeated look - smashed nose; lips sunken in to suggest broken teeth - cauliflower ears (happens when ear injury is ignored; cartilage allowed to overgrow) - nude fighter; hands wrapped in leather bands - blood denoted in copper dripping from face and onto right arm and thigh - copper highlights on lips, nipples, straps on leather gloves, wounds on head - may have been good luck charm for athletes; evidence of toes worn away by touching - thoughtful gaze, hunched shoulders, defeated posture	Seated Boxer	

Archaic through Hellenistic Greek. 600 BCE-150 CE. Plan. - grew out of demand of needs by inhabitants, as opposed to Hippodamian Plan - became seat of ruling body of Athens - plaza at base of Acropolis in Athens; contained commercial, civic, religious, social buildings; ceremonies took place here - setting for Panathenaic Festival; Panathenaic Way cuts through plaza from northwest to southeast corners - plaza surrounded by important buildings, including bouleuterion, tholos, stoas	Athenian Agora	
"- constructed under leadership of Pericles (after Persian sack of Athens in 480 BCE that destroyed original Acropolis) - funded by extra funds in Persian war treasury; Greek allies furious - used algebra and geometry - unusually light interior w/ two windows in cella - floor curves upward in center of facade; drain off rain water; deflect appearance of sagging at ends - columns at ends surrounded by light; made thicker to look same as other columns - Ionic elements in Doric temple: rear room w/ Ionic capitals; frieze on interior Ionic - house massive statue of Athena; made of gold and ivory over wooden core - dedicated to and under protection of Athena - ""architectural contrapposto"""	The Parthenon (from the Acropolis)	

** - Amphiprostyle plan - 
commemorate Greek victory over Persians in Battle of Marathon - many images on victory on temple - cella faces inward toward Acropolis	Temple of Athena Nike (from the Acropolis)	

Asia Minor (present-day Turkey). Hellenistic Greek. c. 175 BCE. Marble (architecture and sculpture).  - altar placed on elevated platform up dramatic flight of stairs - conscious effort to be in dialogue with Panathenaic Frieze on Parthenon - 7 1/2 foot high frieze over 400 feet long wraps around monument - contains altar dedicated to Zeus - Ionic columns frame - battle unfolds as viewers ascend stairs - parallels between King Attalos I's victories over Gauls in recent war, Alexander the Great's defeat of Perisans, and gods' defeat over giants in mythology	Altar of Zeus and Athena at Pergamon	
** Anonymous vase painter of Classical Greece known as the Niobid Painter. 
c. 460-450 BCE. Clay, red-figure technique (white highlights). - found in Orvieto, Italy - one side depiction of the killing of Niobid's children: Niobid bragged about her fertility to god Leto, who only had two children; his two children (Apollo and Artemis) seek revenge by killing Niobid's 12; Niobid punished for her hubris - other side debated; theories: Hercules surrounded by heroes in arms and Athena; warriors of Marathon place themselves under protection of Hercules - first time in vase painting isocephalism not used; may have been under influence of wall paintings	Niobides Krater	

* Republican Roman. c. 100 BCE. Mosaic.
 - Alexander at left: young, brave, forthright, assured of success - Darius in center right on chariot: horrified, weakly ceding victory; charioteer commands horses to make their escape - crowed, w/ nervous excitement - Roman floor mosaic based on original Greek mural (?) painting made by [Philoxenos of Eretria for King Cassander] OR [Helen of Egypt (one of few female Greek artists we know of)] - found at Pompeii - extremely complex interweaving of figures - depicts Battle of Issus: Alexander defeats King Darius III of Perisa	Alexander Mosaic (from the House of Faun)	
** Predynastic Egypt. c. 3000- 2920 BCE. 
Greywacke. - relief sculpture depicted King Narmer uniting Upper and Lower Egypt - hierarchy of scale - used to prepare eye makeup (bc of blinding sun); probably commemorative/ceremonial - believed to compress actions (that took place over many years) into one event - narrative - front: Narmer wears cobra crown (of Lower Egypt) and reviewing beheaded bodies of enemy (bird's eye view' heads carefully placed between legs)  - Narmer preceded by 4 standard bears an a priest; followed by food washer/sandal bearer  - center: harnessed lionesses w/ elongated necks (unification?); bottom symbol of bull knocking down city fortress (Narmer knocking over enemies) - back: Horus as a hawk (god of Egypt) triumphs over Narmer's foes; holds rope around man's head and papyrus plant (symbols of Lower Egypt)  - Narmer w/ bull's tail (symbol of strength) at waist; bowling pin shaped crown as king of united Egypt; beating down enemy; defeated Egyptians lying beneath feet  - servant holding sandals	Palette of King Narmer	
Saqqara, Egypt. Old Kingdom, Fourth Dynasty. c. 2620-2500 BCE. Painted limestone. - created at tomb at Saqqara as provision for the ka - realistic features ---> commoner - color remains - not specific; conventional image of a scribe - attentive expression - thin, angular face - papyrus in lap; right hand once held brush, ready to write - common motif in Egyptian art; needed for abilities -soft body + sagging pectoral muscles = quiet and sedentary lifestyle	Seated Scribe	

** Giza, Egypt. Old Kingdom, Fourth Dynasty. c. 2550-2490 BCE.
 Cut limestone. - giant monuments to dead pharaohs - each w/ enjoining mortuary temple - giant pile of limestone w/ minimal interior; pharaoh buried w/in - oriented to cardinal points - each w/ funerary temple connected by causeway - tombs of pharaohs Menkaura, Khufu, and Khafre	Great Pyramids (Menkaura, Khafre, Khufu)	
- generalized features, but portrait of Khafre (pyramid behind) - carved in situ - body of lion; head of pharaoh and/or god - seems to protect the pyramids - originally painted to stand out in desert - cats royal animals (ancient Egypt), probably because they saved grain supply from mice - head badly mauled in Middle Ages; originally had beard (emblem of pharaohs) - chapel between front feet - connected to Khafre's tomb through passages - erosion + damaging efforts to restore	Great Sphinx (included with Great Pyramids)	

** Old Kingdom, Fourth Dynasty. c. 2490-2472 BCE. 
Greywacke. - figures attached to block of stone (arms and legs) - stare out into space - wife's simple and affectionate gesture and/or presenting him to gods - ankle length and tightly draped gown on queen; same height indicates equality - original location: temple of Menkaura's pyramid complex @ Giza	King Menkaura and queen	

** Karnak, near Luxor, Egypt. New Kingdom, 18th and 19th Dynasties. Temple: 
D: c. 1550 BCE; 
** hall: c. 1250 BCE. 
Cut sandstone and mud brick. - Karnark: center of Amun-Ra's cult (main deity in New Kingdom) - added to for 500 years after initial construction - columns elaborately painted; carved in sunken relief - massive lintels bind columns together - axial plan - tallest columns w/ papyrus capitals - lower columns w/ bud capitals - massive sloped plyon gateway --> peristyle courtyard --> hypostyle hall --> sanctuary (few allowed)	Temple of Amun-Re and Hypostyle Hall	

** Near Luxor, Egypt. New Kingdom, 18th Dynasty.
D: c. 1473-1458 
BCE. Sandstone, partially carved into a rock cliff, and red granite. - 3 colonnaded terraces (originally planted as gardens w/ exotic trees) and 2 ramps - visually coordinated w/ natural setting - first time achievements of a woman are celebrated in art history - body interred somewhere - play homage to ka - never intended to be tomb - bilateral symmetry	

** Mortuary Temple of Hatshepsut	
- one of 200 statues placed around temple; 1/10 of Queen Hatshepsut w/ offering jars (part of ritual to honor sun god) - statue of sun god brought before (in a procession) - inscription on base: offering plants to Amun - mate costume of pharaoh; false beard, kilt - slender proportions and slight breast indicate femininity - white crown of Upper Egypt	Queen Hatshepsut with Offering Jars (from Mortuary Temple of Hatshepsut)	

** New Kingdom (Amarna), 18th Dynasty.
D: c. 1353-1335 BCE. Limestone. - Akhenaton holds eldest daughter (left), ready to be kissed - Nefertiti holds daughter (right) w/ another daughter on shoulder - @ end of sun's rays, ankhs (Egyptian symbol of life) points to king and queen - Amarna period: smoother curved surfaces; low hanging bellies; slack jaws; thin arms; heavy-lidded eyes; awareness of space and depth; genre scene - from altar in a home - Akhenaton and Nefertiti having private relationship with new god, Aton	Akhenaton, Nefertiti, and Three Daughters	

** "New Kingdom, 18th Dynasty.
D: c. 1323 BCE. 
M: Gold with inlay of enamel and semiprecious stones 
- famous tomb discovered by Howard Carter in 1922 - mummified body buried w/ 143 objects on head, neck, abdomen, and limbs; gold mask placed over head - gold coffin 6'7""  - golden mask w/ smoothly idealized features of Tutankhamun; naturalism from Amarna Period in youthfulness of face - holds crook and flail, symbols of Osiris - perhaps physically handicapped caused by genetic inbreeding (parents were siblings) - reigned from ages 9-19 - found in the Valley of the Kings: traditional burial ground of Egyptian kings; naturally protected by cliffs against grave robbers"	Tutankhamun's tomb, innermost coffin	

** New Kingdom, 19th Dynasty. c. 1275 BCE.
 Painted papyrus scroll - illustration from the Book of the Dead (Egyptian book of spells and charms for navigating underworld; helped dead survive test and pass into paradise) -reverts back to traditional presentations - each rigid figure in own niche; flat - Hu-Nefer first kneels before gods and list sins he did not commit (trying to convince he was innocent throughout his life) - Anubis leads Hu-Nefer into hall where is soul is being weighed against a pure ostrich feather; will be condemned is feather is lighter and devoured by hybrid beast Ammit (between scales) - believed heart housed soul of a person - Thoth w/ head of bird writing down these events in hieroglyphics (which he invented) - Osiris (god of underworld) final test before Hu-Nefer can enter afterlife	Last judgment of Hunefer, from his tomb (page from the Book of the Dead)	

** Uruk (modern Warka, Iraq). Sumerian. c. 3500-3000 BCE.
 Mud brick. - deity Anu (god of the sky; most important Sumerian deity) - buttresses spaced across surface to create light and shadow pattern - whitewashed to disguise mud appearance - tapers down so rainwater washes off - temple on top small and removed form populace; access reserved for royalty and clergy - only base remains - interior contains cella and smaller rooms - top terrace for outdoor rituals; temple for indoor - resembles mountain and contrasts with vast flat terrain - built high because gods descend from heaves to high place on earth - four corners oriented to compass	White Temple and its ziggurat	

** "Sumerian. c. 2700 BCE. 
Gypsum inlaid with shell and black limestone. - different heights (hierarchy of scale) - hands folded in gesture of prayer - huge eyes in awe, perhaps staring at the deity - men: bare upper chest; skirt from waist down; bear in ripple patterns; belt - ""It offers prayers"" inscribed on back - representatives of Sumerian worshipers - large, sturdy feet - sometimes hold cups/branches - placed in temple and praying (to Abu?) - found buried in groups under temple floor - hundreds survive - not specific people"	Statues of votive figures, from the Square Temple at Eshnunna (modern Tell Asmar, Iraq)	

** Sumerian. c. 2600-2400 BCE. 
Wood inlaid with shell, lapis lazuli, and red limestone. - reflects extensive trading network: lapis lazuli from Afghanistan; shells from Persian Gulf; red limestone from India - figures w/ broad frontal shoulders, body in profile - emphasized eyes, eyebrows, ears - organized in registers; figures stand on ground lines - narrative to support ruler in a story - left to right, bottom to top - war side: account of warfare where losers suffer injury; enemy soldiers naked (sign of defeat) and marched to be presented to king (in hierarchic scale) - peace side: serene scenes of feasting (possibly of above victory) including servants' preparation of	Standard of Ur from the Royal Tombs at Ur (modern Tell el-Muqayyar, Iraq)	

** Babylon (modern Iran). Susian. c. 1792-1750 BCE. Basalt. - 
right to left, top to bottom - text in Akkadian language - Hammurabi united Mesopotamia and created dominant kingdom - one of earliest law codes ever written - sun god (Shamash) handing Hammurabi ring and rod of kingship (signs of royal power), and rope - Shamash's beard fuller - depicts Hammurabi's ability to approach gods on behalf of people = key feature of authority	The Code of Hammurabi	

** Neo-Assyrian. c. 720-705 BCE. Alabaster. 
- human-headed winged animal guardian figures - five legs (front: standing at attention; side: walking) - wards off in/visible enemies - feeling of harmony and stability - placed at either side of each gate (in Sargon II's city wall at Khorsabad) - bore weight of arches above gates	Lamassu from the citadel of Sargon II, Dur Sharrukin (modern Khorsabad, Iraq)	

** "Persepolis, Iran. Persian. c. 520-465 BCE. Limestone. -
 destroyed by Alexander the Great - seat for spectacular receptions and festivals - on artificial terraces - giant lamassu gates, inscribed as ""The Gate of All Nations"" - relief sculptures depict delegations from all parts of empire bringing gifts to be stored in local treasury - apadana: 36 columns covered by wooden roof; stairways adorned with reliefs of New Year's festival and procession of representatives - columns w/ bell-shaped base (inverted lotus blossom); capitals bulls/lions - Immortals (King's Guard); carved onto stairs - contribution of many cultures - stairs w/ central relief of king enthroned with attendants; crown prince behind him w/ dignitaries bowing  - orderly/harmonious world symbolized by static processions"	Audience Hall (apadana) of Darius and Xerxes	
